### ISSUE TITLE
WiFi is configured as 2 adapters

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#100]
For some reason, it defines two wlan adapters with the same mac (mac is probably wrong). From two of those, wlan1 is active and gets non-configured IP address. Logging in into that address works

**Comment by rinigus** [comment]
In AOSP10, I also have 

```
apollo:/ $ cat /proc/net/wireless                                                                                           
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
 wlan0: 0000    0     0     0        0      0      0      0      0        0
 wlan1: 0000    0     0     0        0      0      0      0      0        0
  p2p0: 0000    0     0     0        0      0      0      0      0        0
```

So, looks to be caused by AOSP10 layer

**Comment by rinigus** [comment]
On Stock Android 10:

```
H8324:/ $ cat /proc/net/wireless                                                                                            
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
 wlan0: 0000    0     0     0        0      0      0      0      0        0
  p2p0: 0000    0     0     0        0      0      0      0      0        0
```

**Comment by rinigus** [comment]
@Thaodan found the corresponding commit: https://github.com/sonyxperiadev/device-sony-tama/commit/ba5a91dfa8046a981cfa8988e7e3fc3e453fc899 . Similar commit is done for other devices as well.

Maybe we would need to let connman blacklist one wlan and not use it.

**Comment by Thaodan** [comment]
Maybe also worth looking into how Android handles it.

**Comment by Thaodan** [comment]
Have you checked if both have the same mac address?

**Comment by rinigus** [comment]
Yes, they do have the same mac and mac looks to be reasonable - Sony domain

**Comment by Thaodan** [comment]
Fixed now:

https://github.com/mer-hybris/droid-src-sony/pull/9

**Comment by rinigus** [comment]
Thank you very much! Will test it in one of the next builds and close as soon as it gets tested.

**Comment by rinigus** [comment]
Yes, this changed removed the second copy of wlan. Networks are shown once and `/proc/net/wireless` lists only one wlan.

Marking it fixed, thank you @Thaodan!
