### ISSUE TITLE
Screen looses touch

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#118]
As for seine:

Touchscreen quite often stops working (to fix: lock the screen - suspend, then wake up)

**Comment by rinigus** [comment]
@pagism and @ApostolosB: please report back whether you have screen loosing touch regularly. On XZ2 all is fine. I know that @pagism had issues during install, but don't know whether it persists. On XZ2c, I had that while developing, but not much now. Hence would be good to get feedback from users of corresponding devices.

**Comment by pagism** [comment]
hi, i had the issue upon initial boot, then i noticed similar behaviour after the first may be sncond reboot, ie having the screen not responding, turn off/on tge screen problem  gone. then after that i have mot noticed it again

**Comment by ApostolosB** [comment]
I didn't notice anything like that or any other issue with touch TBH. If i see something i will report it.

**Comment by rinigus** [comment]
Thank you very much! Then I will close it here and hope that it will not resurface. Although, few updates were added after the issue was filed, maybe something was improved in this respect
