### ISSUE TITLE
Panic after flashing 4.0.1.48

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#130]
Has happened so far only on freshly flashed 4.0.1.48/aosp9 base. At some point of the first boot, after setting all up and installation of Jolla apps (registered wifi connection, Jolla store), phone got into "panic" mode with the LED blinking red. Corresponding MCE message was observed in the logs. Shutdown via long press of power button worked. 

So far, haven't seen it after reboots.

**Comment by lal883** [comment]
Commenting my experience. I just flashed an XZ2C freshly for the first time and have been using it for the past few hours, but fortunately did not experience this. I did connect to a wifi and login to Jolla account and installed Jolla apps during start up. The device was running Android 10 when I received this.

**Comment by rinigus** [comment]
@lal883 thank you for feedback! Let's hope it was just on my device.

**Comment by rinigus** [comment]
Closing as there are no more complains regarding it.
