### ISSUE TITLE
GPS not working in 4.0.1

### ISSUE THREAD

**Issue by ArturGaspar** [sailfishos-sony-tama/main#132]
I updated to 4.0.1 via OTA and GPS no longer works. It finds satellites but never appears to get a fix. Worked fine in 3.4. Device is XZ2 Compact single SIM.
![Captura_de_tela_20210317_001](https://user-images.githubusercontent.com/1616648/111416096-f577a080-86c1-11eb-9bba-40d8db34a664.png)

**Comment by rinigus** [comment]
Just checked on my XZ2c (4.0.1, hybris9 arm32 based port) and it worked fine, GPS fix was obtained. Hard to say, sometimes it may take longer time. Put your phone somewhere where you expect the fix, start some program that will keep the phone awake (I used Pure Maps and entered "Follow me" mode in navigation), and wait 10 minutes or more. It is quick in estimating number of satellites , but fix takes longer. Maybe it is your case.

**Comment by ApostolosB** [comment]
Working fine here also. Tested with the CDS tool.

**Comment by ArturGaspar** [comment]
Got it to work now.

**Comment by rinigus** [comment]
Thank you for update, good to know.
