### ISSUE TITLE
Update sources to match updates in Mer

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#137]
- https://github.com/mer-hybris/droid-src-sony/pull/8
- https://github.com/mer-hybris/android/pull/132

**Comment by Thaodan** [comment]
Merged in :
https://github.com/mer-hybris/android/commit/e6d7de45578379122fc993b95d461bce1acce8dd
https://github.com/mer-hybris/droid-src-sony/commit/6aa63c489c0ed6dd0ed9dfb3aec2b4b71b6d70e6

**Comment by rinigus** [comment]
Yes, I already updated them with refreshing my local copy :) . Forgot to close the issue, as I am making new image.

Closing

**Comment by Thaodan** [comment]
> Yes, I already updated them with refreshing my local copy :) . Forgot to
BTW: Don't make local copies just PR if there are changes needed e.g. adding 
hybris defconfigs for tama.

**Comment by rinigus** [comment]
For kernel we need a special hack that allows it to handle suspend reasonably. But yes, it makes sense to upstream if I can. 

As for this case, these changes are available via updates handled by `repo` and not by our own repositories.

**Comment by Thaodan** [comment]
> For kernel we need a special hack that allows it to handle suspend
> reasonably. But yes, it makes sense to upstream if I can.
Is the hack device specific?

I know how repo manifests work, I thought you forked repos.

**Comment by rinigus** [comment]
Re hack: https://github.com/mer-hybris/android_kernel_sony_msm/commit/65ad0ca39046bb32fa286612ead75692242c35ee

I don't know whether any other device needed it. No idea why it is needed for Tama, but it was pain without it.

Re repo manifests - I am sure you know way more than me regarding it :)

**Comment by Thaodan** [comment]
> Re hack:
> https://github.com/mer-hybris/android_kernel_sony_msm/commit/65ad0ca39046bb
> 32fa286612ead75692242c35ee
>

Have talked to upstream about that one?

**Comment by rinigus** [comment]
You mean Sony OpenDevices? Don't remember, as it was a while ago. I remember we talked about this change on sfos-porters channel, but not sure I talked upstream. Probably, as I asked for help there as well

**Comment by rinigus** [comment]
But it sounds like other devices don't need it on SFOS and on AOSP there was no issue with suspend. So, don't think there is much of an interest in it.

**Comment by Thaodan** [comment]
> But it sounds like other devices don't need it on SFOS and on AOSP there was
> no issue with suspend. So, don't think there is much of an interest in it.
> 
Honestly I did not notice a difference. What made my wonder is that it patches 
non device specific code and should be then relevant to other ports.

**Comment by rinigus** [comment]
You would see if you start looking into suspend failure rate and amount of time it spends in suspend. Something that I noticed with systemdatascope/collectd early in the port.

**Comment by rinigus** [comment]
Sorry, pressed send to early.

Indeed, I was expecting that others will see something similar on SFOS. So far, I don't remember anyone reporting it.
