### ISSUE TITLE
Boot is sometimes stuck on Sony logo

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#14]
Reboot helps usually. To resolve, press power button and it will shutdown fine (red led).

Will have to figure out why it is happening

**Comment by Thaodan** [comment]
Maybe you need to tell the bootloader that the boot was successful? I remember there was similar issue on the XA2 where 5 after boots the boot doesn't worked.

**Comment by rinigus** [comment]
No, that's set alright. I think I had a dmesg from a case like it, will have to paste it here

**Comment by rinigus** [comment]
looks to have disappeared recently, probably with libhybris update. will close after some time if it will not reappear
