### ISSUE TITLE
Hall sensor does not work

### ISSUE THREAD

**Issue by VZuyev** [sailfishos-sony-tama/main#140]
Original Sony Style Cover Stand SCSH40 does not control whether the display is turned on or off when opening and closing.

**Comment by rinigus** [comment]
Does it work with AOSP? If tested, which versions of AOSP?

**Comment by VZuyev** [comment]
The firmware 4.0.1.48 is installed on top of Android 52.1.A.3.49. I have not tested it with AOSP.

**Comment by rinigus** [comment]
Would be good to test with AOSP and see if it works there. As SFOS is based on it, it will need AOSP to function properly

**Comment by VZuyev** [comment]
Please give a link to AOSP.

**Comment by rinigus** [comment]
Good question! I don't have a link ready. But you can look into XDA for your device. Ideally, test AOSP10 (for future) and AOSP9 based versions. Note that you should check whether ROM is AOSP- or stock-based, we need tests against AOSP-based ones. 

For AOSP10 test, you maybe can pull pixelexperience.org, discontinued 10 version. For AOSP9, not sure if there are some links available. In the worst case, you can also build it using Sony OpenDevices guides.

**Comment by VZuyev** [comment]
I was still unable to install the [recovery image ](https://download.pixelexperience.org/h8266) to then install the build. More precisely, I install the recovery image, but I cannot enter it. You have a recovery image that you can install (with the device turned off, hold down the volume down button + plug in the USB cable).

**Comment by rinigus** [comment]
I installed using volume up + plugin usb using fastboot command. but for that, I had to extract partition images. As for using recovery image, maybe you can try to get to fastboot mode and just boot into it (fastboot boot recovery.img) and then flash using it? But probably someone on XDA forums knows how to flash PE

**Comment by VZuyev** [comment]
Yes, I used this command (fastboot boot recovery.img). But I can’t get into the recovery.
I found information on XDA that you first need to use the adb command (adb reboot bootloader). But for this I need to put the stock android again.
How to extract partition images from a build?

**Comment by rinigus** [comment]
Re boot: yes, try before booting into recovery, to `fastboot reboot-bootloader` . It is the same as adb command. 
It is probably a bug in fastboot that you experience. 

As for extracting - I can look it up, but it wasn't trivial and maybe we can get it up without it. You could also try to boot into TWRP for flashing

**Comment by VZuyev** [comment]
I tried all possible options. TWRP does not start. Please give a link to the working TWRP.

**Comment by rinigus** [comment]
Please ask at XDA from TWRP thread for help. I don't use it and neither do I use PE. However, there should be users / developers using these and they should be able to assist you

**Comment by VZuyev** [comment]
Installed AOSP 10. Hall sensor does not work.

**Comment by rinigus** [comment]
@VZuyev : thanks a lot! That means it has to be fixed on AOSP10 side first. Unfortunately, AOSP10 is not developed anymore as they focus on AOSP11. Although, please file the issue at https://github.com/sonyxperiadev/bug_tracker/issues (you can refer to the issue over here as well) and let's see if it is possible to fix on AOSP10 side.

**Comment by VZuyev** [comment]
Posted at [https://github.com/sonyxperiadev/bug_tracker/issues](https://github.com/sonyxperiadev/bug_tracker/issues).

**Comment by mlehtima** [comment]
Are you sure it doesn't need some defconfig fix like the one I did for Xperia 10 II (and other devices also)? I only did that for 4.14 kernel and forgot about the other kernel branches.

**Comment by rinigus** [comment]
No, I am not sure. I was expecting that it is set up in AOSP, but your patches demonstrate that it was probably not the case. Will try to enable

**Comment by rinigus** [comment]
Kernel has been updated in AOSP10/aarch64 version of the port (in testing now, not released). Hopefully Hall sensor is fixed now in that version

**Comment by pagism** [comment]
on XZ3 aosp10 hall sensor is working, or at least CSD passed the test

**Comment by rinigus** [comment]
This is with AOSP10 based port?

**Comment by pagism** [comment]
yes, same device, aosp10

**Comment by rinigus** [comment]
Closing then. Please reopen if it fails to work with AOSP10 based port
