### ISSUE TITLE
Very bright LED

### ISSUE THREAD

**Issue by VZuyev** [sailfishos-sony-tama/main#141]

**Comment by rinigus** [comment]
Is it any different on AOSP or stock Android?

**Comment by VZuyev** [comment]
The firmware 4.0.1.48 is installed on top of Android 52.1.A.3.49.

**Comment by rinigus** [comment]
But was the LED any different in stock before you installed SFOS? Or is it a hardware feature?

**Comment by rinigus** [comment]
Closing as stalled
