### ISSUE TITLE
Hybris-10 on XZ3 upon startup stuck on language setting

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#149]
I had big issues with my XZ3 in the past, so not much confidence so this might be an issue with my phone.

Installation run smoothly without issues, upon start up, after the SONY logo the SFOS splash screen is completely broken, but then after a few seconds SFOS starts and move to the next stage. The language selection page seems to be stuck and the LED is white. There is no response to any language selection or back. Accidentally, I managed to proceed and complete setup by pressing the side on/off button, turning off the screen seems to work, and then tuning on the screen it become responsive to language selection, LED is turned off, and the rest of the setup was completed without further issues.

**Comment by rinigus** [comment]
Let's follow it.

I had to reboot after installation on XZ2; XZ2c was used with AOSP10 for a while - so maybe I just don't remember. Both devices don't have anymore such hiccups though, as far as I can see.

It is possible that the screen lost touch response and it got restored by power off/on.  I have seen it so far only on XZ2c, reported at https://github.com/sailfishos-sony-tama/main/issues/118

However, messed up SONY logo is strange. As for LED, I don't know whether it is expected to be switched on until we choose language.

**Comment by pagism** [comment]
tbh, I had re-flashed the phone and the behaviour was the same in both times, before I realised power off/on restored responsiveness.
The messed up screen is after the SONY logo, and I guess it must be SFOS one?

**Comment by pagism** [comment]
Anyway upon reboot seems to be ok, but again screen is unresponsive, power off, then on seems to restore responsiveness.

**Comment by rinigus** [comment]
I have added a reference to this issue in flashing.md. So, others would know that power off/on helps.

Re screen disturbed after Sony logo: yes, you are right. This should be in SFOS and may relate to incomplete initialization of the screen.

@pagism, please follow whether you have to use power off/on later while using the phone. If it is just once after boot, it is minor annoyance, but it is worse if it does happen frequently. My hope is that it is just initialization which is bit messed up. There was something regarding screen initialization in Jolla's blog when introducing Xperia 10II port. Could be the same here.

If the it repeats frequently during regular use, write a note in https://github.com/sailfishos-sony-tama/main/issues/118 as well.

**Comment by rinigus** [comment]
Closing it here?

**Comment by pagism** [comment]
yes, there is a clear msg in readme, it should save confusion.
