### ISSUE TITLE
Notification LEDs don't blink.

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#151]
When you receive a new SMS, email etc the LED is stationary. 

xz2c hybris 10

**Comment by rinigus** [comment]
Asked about 30 min ago on Porters channel. CSD does show blinking LED without any issues, but notifications are stationary. No idea why, could be SFOS bug as well. Waiting for reply.

**Comment by ApostolosB** [comment]
Ok. Good to know that i am not the only one seeing it.

**Comment by rinigus** [comment]
Closing as upstream bug - reported for Xperia 10II as well. https://forum.sailfishos.org/t/xperia-tama-port-discussion-on-future-direction/7249/10
