### ISSUE TITLE
Camera feedback

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#153]
Camera impressions on AOSP10 SFOS 4.1 using the default camera:
  - stable
  - back camera focus is hit and miss, mostly miss by a little bit, not possible to control
  - front camera very out of focus
  - camera controls: awb, flash, delay, grids work ok, iso settings does not work, but I think it is not working on XA2 either

Using the advanced camera:
  - on manual focus results are better, focusing can be almost sharp
  - switching between back/front cameras makes something like an adjustment noise, not clear it comes from the speaker or something else
  - front camera can focus (automatically) correctly
  - switching to the back camera does not work, requires restarting of the app

Hopefully, all these are fixable ;-)

**Comment by ApostolosB** [comment]
Video also seems to work. And as @pagism said it doesn't crash if you breath near it. Its an improvement. I need to play more with it.

**Comment by rinigus** [comment]
Interesting observation that Advanced Camera is better in following focus. Would have to test it a bit more. Interesting to see what it will be with video as well.

**Comment by pagism** [comment]
Another camera update:
- The default camera can focus better if you let the camera focus (where ever it wants) and take the picture. If you tap on a particular area to focus, it does it on the screen but when taking the picture it seems to re-focus usually somewhere else. The manual mode in advance camera seems to avoid that pitfall.
- Pictures are bright in general and that affects bright parts of an image that get easily overexposed.

**Comment by pagism** [comment]
Few biased sample pictures between XZ3 SFOS default camera, vs AdvancedCamera (IMG_xxx.png) vs XA2, and XZ3 OEM camera:

https://www.dropbox.com/sh/afw21rkn5oe58gp/AAAQ-yNsIIUU7KTgNiwlNpEya?dl=0

Shooting was indoors, and in some pictures there is a camera shake ;-( OEM camera is not a lot better, it does better processing tho.

XA2 default camera ISO controls seem to work, AC although the menu is available iso control does not seem to work.

**Comment by pagism** [comment]
i do not use the camera flash much, but i just noticed it doesn't work for xz3. on the other hand, the torch light seems to work ok (actually it's quite bright)

**Comment by rinigus** [comment]
Camera and flash are very much out of sync on Tama. It is AOSP issue and will not be fixed on AOSP side due to the lack of resources. They did try to do so, but it didn't work out.

**Comment by rinigus** [comment]
Cleanup - closing as non-bug
