### ISSUE TITLE
Add Waydroid support

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#171]
Steps for Waydroid support:

- [x] stop disabling vibrator in /usr/libexec/droid-hybris/system/etc/init/disabled_services.rc
- [x] add Waydroid packages to port. Either from port repos or some central location

**Comment by xsetiadi** [comment]
does this mean it will come by default on the future build of tama devices?

**Comment by rinigus** [comment]
Probably will be as an add-on. If all goes well

**Comment by rinigus** [comment]
Waydroid compatible configuration for vibrator is enabled. Waydroid available via Chum. Closing
