### ISSUE TITLE
MTP not working

### ISSUE THREAD

**Issue by Oluwaseyi14** [sailfishos-sony-tama/main#173]
I just flashed sailfish on my xz2c but can't connect to system to send some files. do I need to install some drivers? Both windows and linux

**Comment by rinigus** [comment]
Just tested - MTP works fine. Used `gmtp` in Linux. Just have to specify in Sailfish Settings/USB corresponding mode ("Always ask" or MTP).

**Comment by Oluwaseyi14** [comment]
Done that still not working

**Comment by rinigus** [comment]
Frankly, no idea why it is not working for you. For me, gmtp detects it as Android device. Have you updated packages after flashing? Please do so and check again.

**Comment by xsetiadi** [comment]
> Frankly, no idea why it is not working for you. For me, gmtp detects it as Android device. Have you updated packages after flashing? Please do so and check again.

on my device, it is detect storage for a second, and then the drive become invisible, like it is not mount properly on sfos

**Comment by rinigus** [comment]
I don't understand what do you mean by "mount properly on sfos". I would expect that on SFOS all partitions are mounted just fine. But mounting them on PC fails. Cannot comment regarding it, as it works fine over here on Linux with gmtp. 

In general, I usually use ssh to transfer data to/from phone. Hence cannot comment very much on day-to-day MTP stability. Just every time I tested, it worked without issues

**Comment by xsetiadi** [comment]
> I don't understand what do you mean by "mount properly on sfos". I would expect that on SFOS all partitions are mounted just fine. But mounting them on PC fails. Cannot comment regarding it, as it works fine over here on Linux with gmtp.
> 
> In general, I usually use ssh to transfer data to/from phone. Hence cannot comment very much on day-to-day MTP stability. Just every time I tested, it worked without issues

idunno, for some reason, after playing with usb-moded.ini file, and got reboot (every time i chose developer mode) now the mtp show up.

**Comment by rinigus** [comment]
Closing as non-reproduced.
