### ISSUE TITLE
Add Chum by default

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#175]
As in https://github.com/HelloVolla/droid-config-yggdrasil/blob/hybris-17/sparse/usr/share/ssu/features.d/chum.ini

**Comment by ApostolosB** [comment]
I'd like to know if Jolla is open -or at least their thoughs- on including chum by "default". Meaning the user to be able to use it by selecting an option somewhere in the settings.

I think of asking it in a next meeting if you don't mind.

**Comment by rinigus** [comment]
Sure, I don't mind. But we have way more freedom with the port and addition of Chum in Tama can be done without any Jolla's blessing.

**Comment by ApostolosB** [comment]
I know that we can be more free but i'd like it if all could enjoy the freedoms chum offers just by tapping an option. I don't expect jolla to say yes but its not a bad thing to ask.

**Comment by rinigus** [comment]
If added then at https://github.com/sailfishos-sony-tama/community-adaptation

**Comment by rinigus** [comment]
That would cause issues with the current Chum users. Let's keep it as additional install that users have to make
