### ISSUE TITLE
WLANs with login page causes crash

### ISSUE THREAD

**Issue by HrGaertner** [sailfishos-sony-tama/main#177]
Hello,
i use a sony xperia xz3 with SFOS

in some open WLANs that have a login page my phone crashes, the same happens after reboot. The only way i found to stop this was quickly logging in and disabling WLAN before the phone crashed again or going out of the WLAN range.

This happened to me in some of the "Deutsche Bahn" Hotspots.

Please tell me how i can help further

**Comment by rinigus** [comment]
Do you know whether it is generic SFOS issue or an issue of our port? I.e has the same crash being reported for official devices?

**Comment by HrGaertner** [comment]
well i searched a bit before opening this issue e.g. "sailfish os crashing hotspot log in " but I did not find anything and since a friend of mine did not have problems in the "Deutsche Bahn" (althogh we did no try it in exactly the same WLAN) how has a supported device, i opened the issue here

**Comment by rinigus** [comment]
Most probably it is some kind of out-of-memory crash. You could try to enable persistent systemd journal and see if we can get some logs out of it. Note that you would have to read through the logs and remove all privacy-sensitive data (phone numbers, IMEI, logins) before uploading them publicly.

**Comment by HrGaertner** [comment]
Ok, i'll have a look how to do this and will write as soon as this issue happened again to me. Thanks!

**Comment by HrGaertner** [comment]
Hello, it has been a while. I could not reproduce the bug. I am sorry.

I do not have SFOS anymore but changed to /e/os since my camera did focus really bad under SFOS and I need that quite frequently in school, so there is no point in leaving this issue open

Thanks a lot for your patience and comments!
