### ISSUE TITLE
4.3.0.12 OTA?

### ISSUE THREAD

**Issue by deprecated-dot** [sailfishos-sony-tama/main#180]
I thought I'd open an issue to draw some attention to it. My daily driver is an Xperia XA2 Ultra with the official SFOS license, but I bought a new XZ2 (h8216) specifically to use with this port. I've been using Sailfish OS since the Nexus 5 community port many years ago, so it's hard for me to live without it now. 

That said, I tried to OTA up to 4.3.0.12 using the instructions on this repository, and it went very well.

Except the camera. When I launch the camera now it's a black screen. Launching it via terminal yields:

`[defaultuser@XperiaXZ2 ~]$ jolla-camera
[D] unknown:0 - Using Wayland-EGL
library "libGLESv2_adreno.so" not found
library "eglSubDriverAndroid.so" not found
[W] unknown:20 - file:///usr/lib64/qt5/qml/com/jolla/camera/settings/CameraDeviceToggle.qml:20: TypeError: Cannot read property 'length' of undefined
[W] unknown:0 - CameraBin error: "Failed to allocate required memory."
[W] unknown:0 - CameraBin error: "Internal data stream error."
[D] onCompleted:105 - ViewPlaceholder requires a SilicaFlickable parent`

`find` shows the libs are present (admittedly, I don't know if the /odm path is correct):

`[root@XperiaXZ2 defaultuser]# find / -name libGLESv2_adreno.so 2> /dev/null
/odm/lib/egl/libGLESv2_adreno.so
/odm/lib64/egl/libGLESv2_adreno.so
[root@XperiaXZ2 defaultuser]# find / -name eglSubDriverAndroid.so 2> /dev/null
/odm/lib/egl/eglSubDriverAndroid.so
/odm/lib64/egl/eglSubDriverAndroid.so`

I know it's a long shot, but do you have any idea where I'd start to solve that? 4.3.0.12 brought some nice changes, so I'd like to use it if at all possible. 

Edit: I know the formatting is goofy, but I think you get the idea. I'm available for testing, logs, etc., no question at all. If you need anything, please let me know.

**Comment by deprecated-dot** [comment]
Apologies, I didn't realize work for 4.3.0.12 wasn't underway yet. I browsed the closed issues and noticed it mentioned before. 

I hope to see it updated in the future. That, or I'll force myself to figure it out myself. 

Thanks!

**Comment by rinigus** [comment]
There is no point in researching it before the update to 4.3 is prepared.
