### ISSUE TITLE
ofono consumes too much power/CPU

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#181]
As the title suggests. I don't know what triggers it exactly but i've seen it more than a few times. Also no idea if this is a port or SFOS bug.

**Comment by rinigus** [comment]
Question: how was it measured or observed?

**Comment by ApostolosB** [comment]
I use top in the terminal. And the phone is a bit warm when this happens.

**Comment by ApostolosB** [comment]
One observation -regarding triggering it- is that it happens when i am in the car. Traveling "long" distances. Might not be the actual cause but i have to report it.

**Comment by rinigus** [comment]
Let's see if you will observe it on 4.3. as well. I haven't seen this with ofono - would be hard to do anything about it.

**Comment by ApostolosB** [comment]
Just want to report that it happens with 4.3 as well. Without me traveling distances. No idea if its related to some ofono related  messages i saw during the update.

**Comment by rinigus** [comment]
I don't think it is related to update messages - I had them as well. And still no issue with ofono for me. I suspect you have to file an issue somewhere in the forum and ask for help. Seems to be more related to your network/device interaction than to the port specifically. But we cannot be sure in that either.

**Comment by ApostolosB** [comment]
Closing this as it is mentioned in the official release notes that the issue has been fixed.
