### ISSUE TITLE
4.3 update - low haptic feedback with keyboard

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#182]
libngf-qt5-qtfeedback seems to lead to rather small (if any) haptic feedback when pressing keys on the keyboard. Pulley menus do provide it, though.

That's when using libhybris 0.0.5.44. Let's see if 0.0.5.42.1 (as in SFOS 4.3 should be) would help

**Comment by pagism** [comment]
interesting, i noticed my xa2 losing haptic twice with 4.3, after rebooting it was ok, not sure it's related with this issue tho

**Comment by rinigus** [comment]
there is new haptic lib, but let's see if bumping back hybris would help. too early to say something for sure and ask for help. here, it is mainly with keyboard

**Comment by rinigus** [comment]
Nope, same with 0.0.5.42.1 hybris. Will ask at IRC

**Comment by rinigus** [comment]
Fixed in https://github.com/sailfishos-sony-tama/droid-config-sony-tama-pie/commit/749147636a42de87b5aac300a27b40df6e4ef644
