### ISSUE TITLE
4.3 update - encryption screen missing touch on some boots

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#183]
With some boot cases, encryption screen does not respond to touch events. 

That's when using libhybris 0.0.5.44. Let's see if 0.0.5.42.1 (as in SFOS 4.3 should be) would help

**Comment by pagism** [comment]
i had the same issue with 4.2 on xz3, i was not sure then if it was a problem with my device and i reflashed it without enabling encryption. Most likely it would be ok if i had rebooted tge phone then.

**Comment by rinigus** [comment]
Looks to be fine now.
