### ISSUE TITLE
OTA to 4.3.0.12 breaks MMS

### ISSUE THREAD

**Issue by deprecated-dot** [sailfishos-sony-tama/main#184]
OTA to latest breaks MMS (see: my [post on forum.sailfishos.org](https://forum.sailfishos.org/t/sharing-image-via-mms-fails-after-4-3-0-12-update/8971/13?u=deprecated)).

It doesn't seem isolated to just this release, as it shows up on other devices/ports. I just wanted to post here in the event it helps someone else. 

A fresh flash to 4.3.0.12 doesn't suffer from this problem. Confirmed everything works (including MMS and camera!) with a fresh 4.3.0.12 flash on my Xperia XZ2.

**Comment by rinigus** [comment]
Thanks for reporting. As it is general SFOS issue, let's close it over here. I would expect here only port-specific issues that we can and should fix.
