### ISSUE TITLE
start-autologin rename defaultuser back to nemo

### ISSUE THREAD

**Issue by teleshoes** [sailfishos-sony-tama/main#186]
is it possible to add a configuration option to restore `nemo` instead of `defaultuser`? ive been doing that manually while applying g7's X Compact patch for my Xc, but i havent figured out how to un-package, tweak, and re-package the image here.

this is all i do to modify the flashing image for my Xc, and it works beautifully:
```
sed -i s/defaultuser/nemo/g /usr/lib/startup/start-autologin
```

**Comment by rinigus** [comment]
No, that would be splitting from official SFOS version and, while tempting when it was introduced, it was decided to stick to SFOS default.

**Comment by teleshoes** [comment]
:'(

**Comment by rinigus** [comment]
felt the same when it happened.

**Comment by rinigus** [comment]
Closing here

**Comment by teleshoes** [comment]
just discovered guestfish! what a wonderful little tool, fixes this insane problem perfectly

https://github.com/teleshoes/sx-config/blob/b9929aa63389275eeeeba5f36f6e76ab84fa50e9/tools/fix-image-flashing-xz2c.pl
