### ISSUE TITLE
ofono - sim card not working

### ISSUE THREAD

**Issue by teleshoes** [sailfishos-sony-tama/main#187]
when i first flashes tama, it was fine. i put my sim card in, made a call, sent an SMS, sent an MMS, and used LTE to check my download speed.

i then removed my sim card, put it back in my X Compact, and prepared my new phone, building aarch64 rpms for all the crap i use.

when i finally put the sim card back in, i get nothing from ofono

ive tried, in decreasing order of obviousness:
- rebooting (still nothing)
- removing the sim card, and replacing it, and rebooting (still nothing)
- checking ofono logs (no particular help googling my errors)
- placing the sim card back in X Compact (instantly works, good as ever)
- placing the sim card in ANOTHER X Compact (works good as ever)
- setting Prefer 3G (nothing)
- putting the sim card back and waiting an hour (nothing)
- re-setting the sim card while the phone is running (nothing)
- re-flashing the SFOS tama image

and im sure i forgot a few other things ive tried. im really bummed, this build on this device is the best SFOS experience ive had. particularly love waydroid...

**Comment by teleshoes** [comment]
ofono logs look like this on initial boot and after restarting ofono
```
Jan 25 16:50:16 XperiaXZ2Compact ofonod[17067]: [gbinder-radio] Connected to android.hardware.radio@1.2::IRadio/slot1
Jan 25 16:50:16 XperiaXZ2Compact ofonod[17067]: slot1 version 102
Jan 25 16:50:16 XperiaXZ2Compact ofonod[17067]: SIM card OK
Jan 25 16:50:21 XperiaXZ2Compact ofonod[17067]: Requested file structure differs from SIM: 6fb7
Jan 25 16:50:21 XperiaXZ2Compact ofonod[17067]: session_read_info not implemented
Jan 25 16:50:21 XperiaXZ2Compact ofonod[17067]: SMS History Probe for modem: 0x35997130
Jan 25 16:50:21 XperiaXZ2Compact ofonod[17067]: Registered interface org.ofono.NetworkTime, path /ril_0
Jan 25 16:50:21 XperiaXZ2Compact ofonod[17067]: nw selection is already auto
Jan 25 16:50:21 XperiaXZ2Compact ofonod[17067]: Requested file structure differs from SIM: 6fb7
Jan 25 16:50:22 XperiaXZ2Compact ofonod[17067]: export_entries_one_storage_cb with ME failed
```

i can see my card ID and subscriber ID with dbus calls, so sim card is at least kinda working
`/usr/lib64/qt5/bin/qdbus --system org.ofono /ril_0 org.ofono.SimManager.GetProperties`
```
BarredDialing: false
CardIdentifier: 8888888888888888888
FixedDialing: false
LockedPins: MobileCountryCode: 310
MobileNetworkCode: 260
PinRequired: none
PreferredLanguages: en
Present: true
SubscriberIdentity: 333333333333333
SubscriberNumbers: 15551231234
```

SubscriberNumbers changed (it was my real phone number)
CardIdentifier changed (started with 8)
SubscriberIdentity changed (started with 3)

**Comment by teleshoes** [comment]
GAHHH it works on aosp9 4.0.1.48
:'(

EDIT: 2G-only works on aosp9. aosp10, still nothing at all.

i am SURE that LTE was working, briefly, at 11mbps, on aosp10 4.3.0.12, on the same sim card.

**Comment by teleshoes** [comment]
after trying a BILLION things, flashing stock DoCoMo SO-05K with xperifirm+newflasher, and then reflashing SFOS 4.3 (aosp10), worked!
4G is working again!

lets hope it survives a reboot :)

**Comment by rinigus** [comment]
I was going to suggest to flash stock and update that to Android 10 before going AOSP10/SFOS route. Sounds like you did that

**Comment by teleshoes** [comment]
actually, i tried that and it failed.

what worked was going to Android9 stock (japan/docomo), booting it and checking LTE, and then flashing directly to SFOS-AOSP10

**Comment by teleshoes** [comment]
(btw, i still never got a vanilla aosp10 to boot on this phone. none of the aosp images ive found will flash, only stock sony and sfos)

**Comment by rinigus** [comment]
As the issue seems to be resolved, closing
