### ISSUE TITLE
slow 4G internet in waydroid

### ISSUE THREAD

**Issue by teleshoes** [sailfishos-sony-tama/main#189]
this may be a waydroid issue, or it may be a sailfish issue, or a telecom issue, or just a me issue. forgive me if this is the wrong venue.

the symptom on my XZ2c running 4.3 aosp10:
on LTE, android apps (e.g.: bromite) get 200kbps, and sailfish apps (e.g.: sailfish-browser) 8,500kbps. (LTE is shitty here)
on WiFi, they both get 345,000kbps.

on a side note, aliendalvik 8 on XA2 and aliendalvik4 on  Xperia X does not have this symptom, and stock android9 on XZ2c does not have this symptom, all get 8+mbps on LTE.

i have a possible explanation, which is that my telecom is throttling me. T-Mobile provides two different bandwidth caps, one for 'device' and one for 'hotspot'. im not sure this is the problem, though, as the cap is usually 20-40kbps.

on my laptop, i get around this throttling a socks proxy on my laptop, and i might be able to do the same on android for some apps, but not others.

is it expected that i would have a different mac (or whatever they might be using to check) from waydroid? i dont have any idea how the routing actually works. if the issue is the throttling, might i be able to fix this at the system level?

**Comment by rinigus** [comment]
Just checked, I have 20Mbps in Waydroid and SFOS (within some margin, +-5Mbps). So, it is your provider. Note that Waydroid connection is probably similar to hotspot-like one. 

Closing here.
