### ISSUE TITLE
Untypical Linebreak in German language on XZ2 Compact-Port

### ISSUE THREAD

**Issue by FingusDE** [sailfishos-sony-tama/main#197]
I am not sure if this is Port-Specific, so i first post it here and wait for suggestions.

Font size is set to normal (smallest choice).

![Bildschirmfoto_20230213_002](https://user-images.githubusercontent.com/48802630/218505447-318d8ba7-b561-47e2-b6c6-0e8d2e41907a.png)

**Comment by rinigus** [comment]
That's something I am not having control over at port level, I think. I guess we are hitting screen sizes not tested by Jolla. Closing it here, please open at Sailfish Forum
