### ISSUE TITLE
Compass is broken

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#20]
shows a lot of updates. will have to check it further

**Comment by pagism** [comment]
compass seems to be working, compared to another android phone is about +40° off

**Comment by rinigus** [comment]
Compass needs the currently recommended approach for Android phones: use of magnetometer together with accelometer. Compass code is available, but not merged to Qt https://codereview.qt-project.org/c/qt/qtsensors/+/92017

We can probably lift it and incorporate into the qt sensors. For now, compass at https://github.com/janbar/harbour-compass works

**Comment by rinigus** [comment]
Fixed through new sensors in sensorfwd. Released via OTA
