### ISSUE TITLE
Please support XZ3(H9493) 

### ISSUE THREAD

**Issue by qingfengmuxia** [sailfishos-sony-tama/main#201]
when i runing the 'flash-on-windows.bat', i was stick in the 'Searching for a compatible device...', i think maybe this script only support the 
H9436 and not include H9493. And i think this two phone was the same model call XZ3. Hope the team can support H9493, i am excited to try the sailfishos. the difference between this two phones just the Ram.

**Comment by rinigus** [comment]
I have no way of testing on windows nor on that device. There are probably couple of users with this device and, if it works, you can use some workaround for flashing it. For example, manually. For some reason this device is not a part of Sony open devices program, no idea why.

**Comment by qingfengmuxia** [comment]
> I have no way of testing on windows nor on that device. There are probably couple of users with this device and, if it works, you can use some workaround for flashing it. For example, manually. For some reason this device is not a part of Sony open devices program, no idea why.

Thanks for your reply, it's good to get a conclusion. And know why you don't include this device in the flashing script.  Maybe I'll try that way later when I have time.
