### ISSUE TITLE
ufshcd_ioctl: User buffer is NULL

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#21]
journal is full of messages like

```
ufshcd-qcom 1d84000.ufshc: ufshcd_ioctl: User buffer is NULL!
```

**Comment by lingliua** [comment]
Hi rinigus :
Have you found the root cause of the question.
I have encountered the same problem. If you have resolved it, can you please share some experience to me ?
Thanks

**Comment by rinigus** [comment]
No, not really. For you, is it with using this port?

**Comment by lingliua** [comment]
Yes, the log is the same as yours.

**Comment by Thaodan** [comment]
Apparently its cause by this line:
https://github.com/sonyxperiadev/kernel/blob/d8fd4ac9efb7fa69a7be4da7444b25d42ae8af42/drivers/scsi/ufs/ufshcd.c#L9551

**Comment by Thaodan** [comment]
The question is: is it a hardware bug which is not fixable and making this better to be a warning than an error or its a software bug somewhere else requiring a fix.

**Comment by rinigus** [comment]
That is hard to know, isn't it? I had those in Android as well, if I remember correctly.

**Comment by hacker1024** [comment]
I'm getting these in my Halium port on the Xiaomi Redmi K20 Pro, too.

**Comment by rinigus** [comment]
Same on Android, closing
