### ISSUE TITLE
Fingerprint sensor support missing

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#23]

**Comment by ApostolosB** [comment]
Is there a chance for the fingerprint sensor to work on SFOS??? Works on AOSP and i think i saw something related to it mentioned in the logs while on SFOS.

**Comment by rinigus** [comment]
There is a chance. We may have to write open-source alternative to the current closed-source implementation. Currently, unofficial devices don't have the support. Will have to raise it with Jolla. For now, though, I better focus on getting your device working and other bugs/issues with the port

**Comment by ApostolosB** [comment]
Obviously there is no rush. A usable phone first. I was just curious. And i didn't know FP support was a closed feature for official phones. I thought it was hybris or something else that made it not work.
Anyway. First things first.

**Comment by ApostolosB** [comment]
@rinigus Do you have "a plan" on how to move forward with this?? I mean are you going to put it up for discussion in a Community meeting or discuss it with someone from jolla privately??

**Comment by rinigus** [comment]
I am usually absent on the meetings as I have a work to do at that time. If you participate, feel free to propose.

With the respect of this issue, my current plan is to ask at IRC again after a bit of time (1-2 weeks, feel free to remind) and, if nothing comes out, consider implementing it with new code. Would feel silly to do so, though, and would prefer to work on aspects that don't duplicate others work.

**Comment by ApostolosB** [comment]
OK. I will propose it on the one we have on the 9th of january. You can read the logs in the afternoon.

**Comment by ApostolosB** [comment]
http://merproject.org/meetings/mer-meeting/2020/mer-meeting.2020-01-09-09.00.log.html

Logs of what went down. To me it appears jolla is confused with that. Probably someone needs to bring it up in the mailing list -for better visibility- and i 'am certainly going to ask for an update on the situation in two meetings time. Other than that jolla has to discuss it internally and provide info.

**Comment by rinigus** [comment]
Thanks for raising it. And if you can, would be great to continue. Not sure whether NDA and working on closed-source bits will be good long term solution. That would have to be thought through as we could end up on the same situation later. Also open-source maybe of help for other mobile Linux distros out there.

**Comment by ApostolosB** [comment]
The main thing is we have no clear answer. Jaymzz mentioned big paying customers and them (jolla) needing to be careful but i cant make the connection on how this might affect other customers. And jolla doesn't have a CEO that is close to the community and can make things happen. Its a weird situation. -same in a way with pure maps on the store- All i can do is just bring it up from time to time.

:frowning_face:

**Comment by ApostolosB** [comment]
@abranson said to ask about redistribution on a next meeting. I have no understanding about that so probably someone has to write a question.

**Comment by rinigus** [comment]
Sounded that they are working on it, which is excellent. Let's wait and ask not on the next one but the next meeting after that.

**Comment by ApostolosB** [comment]
@rinigus i am not in a rush. Its just that someone more competent on the subject than me has to ask it since i didn't understand the whole discussion. 
But yes. They work on it and that is nice :smile:

**Comment by ApostolosB** [comment]
Kind of unrelated but noticed that when you have fingerterm open and touch/drag fingers on the sensor you get input (similar to arrows on a keyboard). Is this normal??

**Comment by rinigus** [comment]
Interesting. Can't get it work that way over here, but I have unloaded FP reader on my phone and already have changes merged with it to be pushed as a part of next SFOS release.

**Comment by rinigus** [comment]
Heads up: this is coming thanks to work by piggz. Joined his effort and I am sure it will end up on your devices at some point in the near(ish ) future.

**Comment by ApostolosB** [comment]
nice nice nice NIIIIIIIIIIIIIIIICCCCCCCCEEEEEEEEEEEEEEEEEEE

thanks all.

**Comment by ApostolosB** [comment]
A question because out of excitement i forgot to ask. Is this in collaboration with jolla or a totally new separate implementation. They said they were going to make things easier.

**Comment by rinigus** [comment]
:) its a new implementation. Piggz reverse engineered API and used Ubuntu Touch code. Right now we are getting helpful insights from Jolla developer as well - I presume that allows them to help us without any licensing issues they were running into.

**Comment by ApostolosB** [comment]
Its kind of idiotic to have two implementations of the same thing but yeah. I ll take it over no function.

**Comment by rinigus** [comment]
It is impossible to judge. As far as I understood, Jolla was payed by someone to make it. That someone was not thrilled in releasing it as open-source, or maybe even couldn't do that for some reasons. However, Jolla folks are happy to help and we  get tips regarding implementation as well as warnings on what to avoid. In the end, its probably the only way to do it.

**Comment by rinigus** [comment]
note to myself: revert https://github.com/sailfishos-sony-tama/droid-config-sony-tama-pie/commit/bcd98ad6071f318b9f04e4b147c6967e8995b6bf

**Comment by rinigus** [comment]
Just uploaded all to OBS and should be ready for testing. Would you mind to test before announcement?

To test, as root:

```
zypper ref
zypper up
```

It should install new packages droid-biometry-fp sailfish-fpd-community-test sailfish-fpd-community and sailfish-devicelock-fpd. At the same time, it should remove another package with devicelock that we used without fingerprint. Also few config packages should be updated.

After update, reboot

To add/remove fingerprints, please use Fingerprint app that should have got installed. Assuming that you have PIN for devicelock login, all should work.

If you start adding fingerprints in settings app, you may hit https://github.com/piggz/sailfish-fpd-community/issues/10 . If all works, try to test that as well and report on your status.

**Comment by ApostolosB** [comment]
hmmm

i did a devel-su zypper ref and devel-su zypper up and dont see any fingerprint stuff installed.

**Comment by rinigus** [comment]
let's try again:

```
devel-su zypper clean -a
devel-su zypper ref -f
version --dup
```

if that fails and no fingerprint is installed, then try

`devel-su zypper in sailfish-fpd-community-test sailfish-fpd-community sailfish-devicelock-fpd`

It may complain and tell that you need to uninstall something. Ideally copy it over here as well as comment to the issue before doing something radical.

**Comment by ApostolosB** [comment]
The above didn't install anything 

the manual installation gave me:

```
devel-su zypper in sailfish-fpd-community-test sailfish-fpd-community sailfish-devicelock-fpd
Password:
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: sailfish-devicelock-fpd-1.0.8-1.5.6.jolla.armv7hl conflicts with jolla-devicelock-plugin-encsfa provided by jolla-devicelock-plugin-encsfa-0.2.37-1.9.6.jolla.armv7hl
 Solution 1: Following actions will be done:
  deinstallation of jolla-devicelock-plugin-encsfa-0.2.37-1.9.6.jolla.armv7hl
  deinstallation of jolla-devicelock-daemon-encsfa-0.2.37-1.9.6.jolla.armv7hl
 Solution 2: do not install sailfish-devicelock-fpd-1.0.8-1.5.6.jolla.armv7hl

Choose from above solutions by number or cancel [1/2/c] (c):
```

**Comment by rinigus** [comment]
Thank you very much for pasting it - we will be able to put it into docs. Choose 1 (deinstallation of jolla-devicelock-plugin-encsfa) and then, after install, reboot

**Comment by rinigus** [comment]
@ApostolosB, did it work for you?

**Comment by ApostolosB** [comment]
@rinigus was out for a beer hence the delay.

I added a finger with the app and it seems to work ok. Unlocks after i wake up the device. Same thing with the fingerprint add from the settings no reboots or something but i didn't abuse it. Just added one finger. 

Also it seems reasonably fast to me but i don't have experience unlocking devices that way.

One nitpick would be that the finger names on the up don't correspond correctly to the setting ones and vise versa.

**Comment by rinigus** [comment]
Excellent! Then it looks to be resolved. As for names, there is nothing we can do. Those names are assigned by Jolla's Settings and there is no access to that. Closing and announcing in the list. Enjoy!

**Comment by ApostolosB** [comment]
Regarding names. 
In the app you can type a name. In the settings fingertips appear as Fingertip 1 Fingertip 2. In the app i have _name i gave_ and finger1 for the one i assigned from the settings. 

it will be less "confusing" if Fingertip 1 Fingertip 2 also appeared on the app. It not a big deal or something but might be a problem for some if they try to remove a fingertip from the app or the settings. 
As i said its a small detail. Not a big issue.
