### ISSUE TITLE
consider adding presage keyboards to base install

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#26]

**Comment by ApostolosB** [comment]
Today in the meeting ljo mentioned something about him rewriting functionality we need from pressage. I have no idea what this is all about but i know for sure i need text prediction in Greek. And other languages in general.

**Comment by rinigus** [comment]
Yes, @ljo mentioned it, indeed - I saw from the logs. Its excellent news and it sounds like its proceeding well. I am not sure whether you will need unicode screen handling, the current setup may just work. 

But with https://github.com/sailfish-keyboard , you "just" need to get your hands on representative text. Note that we have already few languages covered at OpenRepos

**Comment by rinigus** [comment]
PS: That representative text should be rather large. I think we explained the procedure somewhere (TMO or TJC in addition to READMEs in the projects). Can't recall where though

**Comment by ApostolosB** [comment]
http://talk.maemo.org/showthread.php?t=100266 this ???

**Comment by rinigus** [comment]
Yes. Look into the thread it also explains how to make new languages possible, as for Greek

**Comment by rinigus** [comment]
Closing it without adding. Its in general considered to be better as bare bones as possible with ports. Users can add keyboard later
