### ISSUE TITLE
Suspend limited to shorter ones

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#27]
On AOSP, without network, suspend times are relatively long, as several minutes. On Sailfish, we get about 10 seconds on average.

**Comment by rinigus** [comment]
Sometimes, we have bursts of suspend failures, as it was early in the porting. Will have to follow which wakelocks are causing it.

**Comment by rinigus** [comment]
In flight mode, we get 150s suspend duration - same period as set for collectd, so its working as expected. So, for full offline we are in a clear, its behaving exactly as expected.

**Comment by rinigus** [comment]
2G, without net, suspend easily reaches 60s+, up to 150s

3G, no network: probably towards 10s+, not enough data yet

4G, no network: suspend is 8-14s usually (or 6-20s, more inclusive). average 9.7s

4G, with network: suspend is on average 3.4s

**Comment by rinigus** [comment]
From looking into my logs (3G or 4G with net) and logs by @pagism (wifi, https://github.com/sailfishos-sony-tama/main/issues/55#issuecomment-568797644), I get the most frequent wakeup source as `c440000.qcom,spmi:qcom,pmi8998@2:qpnp,fg`. This should be coming from https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/drivers/power/supply/qcom/qpnp-fg-gen3.c 

Rate is about once per 12-13 seconds

**Comment by pagism** [comment]
my understanding is that all those issues are interrelated. i do not know much about wakelocks, but i am happy to provide logs for various scenarios for xz3 and xa2 for comparison?

**Comment by rinigus** [comment]
They pretty much are the same. The more frequent wakeups than needed keep the device working while it should be at rest. So, if we can get the phone sleep for longer, we should get better battery life as well.

**Comment by rinigus** [comment]
Re logs: I'll keep it in mind. :)

**Comment by rinigus** [comment]
Its possible that `c440000.qcom,spmi:qcom,pmi8998@2:qpnp,fg` is a red herring. Namely, it seems that this wakeup source is processed every time the device wakes up. As such, total counts of wakeup sources are way larger than expected on average sleep time showing that several are processed every time. See also commit introducing the stats: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=30e3ce6dcbe3fc29c343b17e768b07d4a795de21

Taking this into account, the other significant wakeup sources are

mce_input_handler
sensor_ssc_cq
mce_mux
IPCRTR_mpss_rx
mpss_IPCRTR
qcom-step-chg
usb_moded_input

Now would have to go through the modes and see where are they triggered.

**Comment by pagism** [comment]
how do we associate wakelocks with process names? logs can be easily sorted e.g. top 12 wakeup_counts:

![Untitled](https://user-images.githubusercontent.com/59111727/72762934-5cdab300-3bd9-11ea-9a12-5e9e45f0cafa.png)

**Comment by rinigus** [comment]
Yes, I have similar spreadsheets on my PC as well :)

Its mainly grep of kernel and mer sources. And a bit of persistence to find them. In general, it looks to me that the wakeups are caused by open internet connections. They seem to lead to interrupts and wakeup the device. As we have very chatty battery driver (chatty in terms of sending lots of udev messages), we get extra processing by udev handling in SFOS on every wakeup. 

It does help to stop google talk (xmpp) connection in my case, probably to drop to 3G. But will have to think what can we do to help. From comparing our graphs with xperia 10 on cpu sleep, I must say our state is way better.

**Comment by pagism** [comment]
Old good grep then! Can you send me the links of the keenel and mer source code please?

In my case i had a noticeable improvement  turning to manual updates for accounts. The worst one in my case is the Twitter account which by default  updates every 15minutes.

**Comment by rinigus** [comment]
Kernel: right now we use https://github.com/sailfishos-sony-tama/android_kernel_sony_msm/tree/hybris-sony-aosp-9.0.0-4.9-tama-sony

Re 15 min: taking into account that the wakeups are in seconds, 15 min shouldn't be a problem. Unless it keeps connection intact (`lsof -i`). When connected, I have few connections with DNS kept and they could be causing interrupts. Run `lsof -i` as root to see what's open.

**Comment by pagism** [comment]
My lsof -i, it should not have active connections, dev mode and ssh are on.

```
COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
systemd     1 root   38u  IPv6    34537      0t0  TCP *:ssh (LISTEN)
connmand 3326 root   17u  IPv4    19259      0t0  UDP localhost:domain 
connmand 3326 root   18u  IPv6    19263      0t0  UDP ip6-localhost:domain 
connmand 3326 root   19u  IPv4    19267      0t0  TCP localhost:domain (LISTEN)
connmand 3326 root   20u  IPv6    19271      0t0  TCP ip6-localhost:domain (LISTEN)
connmand 3326 root   24u  IPv4 21709817      0t0  UDP *:39676 
connmand 3326 root   26u  IPv4 21711568      0t0  UDP jollaxz3.wcat.local:53127->DD-WRT1:domain 
connmand 3326 root   28u  IPv4   479251      0t0  UDP localhost:51144->localhost:domain 
connmand 3326 root   29u  IPv6   479252      0t0  UDP ip6-localhost:52414->ip6-localhost:domain 
connmand 3326 root   30u  IPv4 21711570      0t0  UDP jollaxz3.wcat.local:55213->DD-WRT1:domain 
connmand 3326 root   31u  IPv4 21712864      0t0  UDP jollaxz3.wcat.local:44701->DD-WRT1:domain 
systemd  3600 nemo   25u  IPv4 21325196      0t0  TCP localhost:8553 (LISTEN)
```

**Comment by pagism** [comment]
c440000.qcom.spmi:qcom.pmi8998@2:qpnp.fg is used a lot, but it's hard to decipher it, c440000 must be an address to spmi bus, and pmi8998 is not clear to me it seems to do lots, qpnp.fg is trying to read battery properties.

**Comment by rinigus** [comment]
that one is tracked down, see https://github.com/sailfishos-sony-tama/main/issues/27#issuecomment-576051510 . but, I am convinced that its not primary cause, see yesterday comments as well

**Comment by rinigus** [comment]
Right now I am drawing blank a bit, will work on other things and plan to come back later. 

While battery is probably just working on every wakeup, its also emitting quite a few uevents. In these events, nothing is changed except sequence number:

```
UDEV  [51082.528258] change   /devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pmi8998@2:qcom,qpnp-smb2/power_supply/battery (power_supply)
ACTION=change
DEVPATH=/devices/platform/soc/c440000.qcom,spmi/spmi-0/spmi0-02/c440000.qcom,spmi:qcom,pmi8998@2:qcom,qpnp-smb2/power_supply/battery
PLATFORM_DEVICE=c440000.qcom,spmi
PLATFORM_FOLDER=soc
POWER_SUPPLY_CAPACITY=91
POWER_SUPPLY_CHARGER_TEMP_MAX=803
POWER_SUPPLY_CHARGE_CONTROL_LIMIT=0
POWER_SUPPLY_CHARGE_CONTROL_LIMIT_MAX=15
POWER_SUPPLY_CHARGE_COUNTER=2824455
POWER_SUPPLY_CHARGE_DONE=0
POWER_SUPPLY_CHARGE_FULL=3217000
POWER_SUPPLY_CHARGE_FULL_DESIGN=3217000
POWER_SUPPLY_CHARGE_TYPE=N/A
POWER_SUPPLY_CHARGING_ENABLED=1
POWER_SUPPLY_CONSTANT_CHARGE_CURRENT_MAX=2275000
POWER_SUPPLY_CURRENT_NOW=25390
POWER_SUPPLY_CURRENT_QNOVO=-22
POWER_SUPPLY_DIE_HEALTH=Cool
POWER_SUPPLY_DP_DM=0
POWER_SUPPLY_HEALTH=Good
POWER_SUPPLY_INPUT_CURRENT_LIMITED=0
POWER_SUPPLY_INPUT_SUSPEND=0
POWER_SUPPLY_LRC_ENABLE=0
POWER_SUPPLY_LRC_NOT_STARTUP=0
POWER_SUPPLY_LRC_SOCMAX=0
POWER_SUPPLY_LRC_SOCMIN=0
POWER_SUPPLY_MAX_CHARGE_CURRENT=-22
POWER_SUPPLY_NAME=battery
POWER_SUPPLY_PARALLEL_DISABLE=0
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_REAL_TEMP=270
POWER_SUPPLY_RERUN_AICL=0
POWER_SUPPLY_RUNNING_STATUS=0
POWER_SUPPLY_SET_SHIP_MODE=0
POWER_SUPPLY_SMART_CHARGING_ACTIVATION=0
POWER_SUPPLY_SMART_CHARGING_INTERRUPTION=0
POWER_SUPPLY_SMART_CHARGING_STATUS=0
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_STEP_CHARGING_ENABLED=0
POWER_SUPPLY_SW_JEITA_ENABLED=0
POWER_SUPPLY_SYSTEM_TEMP_LEVEL=0
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_TEMP=270
POWER_SUPPLY_VOLTAGE_MAX=4380000
POWER_SUPPLY_VOLTAGE_NOW=4195545
POWER_SUPPLY_VOLTAGE_QNOVO=-22
SEQNUM=490954
SUBSYSTEM=power_supply
USEC_INITIALIZED=5010862
bootdevice=1d84000.ufshc
```

SFOS is not very happy about it as it is processing and checking out every one of them. Ideally, this spam should end. But it maybe not the major concern as such in terms of wakeups.

We will also transit to kernel 4.14 at some time. Maybe should revisit it then.

**Comment by pagism** [comment]
that's ok, thanks for your efforts, I have not realised that everything in mobile is so tightly monitored against resource usage. I guess Jolla is not very keen in tama devices porting, anyway I look forward for kernel 4.14 transition.

**Comment by rinigus** [comment]
Part of the discussion, some logs, available at #55.

**Comment by pagism** [comment]
Observation: battery life is good with minimal usage of the phone, today I used the phone to take a picture, and opened the gallery too. Since then battery consumption got high ~9% per hour.

**Comment by rinigus** [comment]
That suggests that some tracker or some other process got crazy and the phone is not sleeping either. For comparison, without photos, I admit, but 'normal' day use, I had 11% (87 to 76%) during 12h

**Comment by pagism** [comment]
I had similar experience to yours, however using the camera or the gallery seems to trigger some process in to rouge state. Interestingly, holding the device it felt warm so I was expecting high consumption before even turning display on.

**Comment by rinigus** [comment]
Makes sense. Try to see what is causing it... top, journalctl are your friends

**Comment by pagism** [comment]
well I had to reboot the device or I was running very low battery. Anyway after rebooting and charging I think I got into a similar situation, i.e. camera misbehaved.
Although all apps are closed top shows the following process to be present
```
 3624 cameras+  20   0  146552  50524  15980 S   0.3   1.3   0:08.74 provider@2.4-se 
```
journalctl has many messages 
```
Jan 29 21:22:35 Sailfish kernel: CAM_INFO: CAM-CRM: __cam_req_mgr_traverse: 288 Skip Frame: req: 5 not ready pd: 2 open_req count: 
1
```
also there is some activity related to fingerprint?
```
Jan 29 21:22:28 Sailfish kernel: QSEECOM: qseecom_load_app: App with id 414 (fpctzfingerprint) now loaded
Jan 29 21:22:28 Sailfish kernel: CAM_INFO: CAM-CRM: __cam_req_mgr_traverse: 288 Skip Frame: req: 5 not ready pd: 2 open_req count: 
1
Jan 29 21:22:28 Sailfish kernel: ptrace attach of "/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service.sony"[2
5846] was attempted by "crash_dump64 25807 25841 1"[25843]
Jan 29 21:22:28 Sailfish kernel: CPU1: update max cpu_capacity 306
Jan 29 21:22:28 Sailfish audit[25807]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=kernel pid=25807 comm="andr
oid.hardwar" exe="/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service.sony" sig=6
Jan 29 21:22:28 Sailfish unknown: type=1701 audit(1580332935.220:544): auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=
kernel pid=25573 comm="android.hardwar" exe="/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service.sony" sig=6
Jan 29 21:22:28 Sailfish unknown: type=1701 audit(1580332948.329:545): auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=
kernel pid=25807 comm="android.hardwar" exe="/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service.sony" sig=6
Jan 29 21:22:28 Sailfish kernel: QSEECOM: qseecom_unload_app: App id 414 now unloaded
Jan 29 21:22:28 Sailfish lipstick[4342]: [C] unknown:0 - evdevkeyboard: Could not read from input device (No such device)
Jan 29 21:22:28 Sailfish droid-hal-init: Service 'fps_hal' (pid 25807) received signal 6
Jan 29 21:22:28 Sailfish droid-hal-init: Sending signal 9 to service 'fps_hal' (pid 25807) process group... HYBRIS: killing PID ins
tead of process group.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/event7/enable' f
ailed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown root:input /sys//devices/virtual/input/input418/event7/ena
ble' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/event7/poll_dela
y' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown root:input /sys//devices/virtual/input/input418/event7/pol
l_delay' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/event7/poll' fai
led with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown input:system /sys//devices/virtual/input/input418/event7/p
oll' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/event7/pollrate_
ms' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown input:system /sys//devices/virtual/input/input418/event7/p
ollrate_ms' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/event7/enable_ps
_sensor' failed with exit code 1.
Jan 29 21:22:28 Sailfish kernel: CAM_INFO: CAM-CRM: __cam_req_mgr_traverse: 288 Skip Frame: req: 5 not ready pd: 2 open_req count: 
1
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown system:system /sys//devices/virtual/input/input418/event7/
enable_ps_sensor' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/event7/set_delay
_ms' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown system:system /sys//devices/virtual/input/input418/event7/
set_delay_ms' failed with exit code 1.
Jan 29 21:22:28 Sailfish lipstick[4342]: [W] unknown:0 - evdevkeyboard: Failed to query led states
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/enable' failed w
ith exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown root:input /sys//devices/virtual/input/input418/enable' fa
iled with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/poll_delay' fail
ed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown root:input /sys//devices/virtual/input/input418/poll_delay
' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/poll' failed wit
h exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown input:system /sys//devices/virtual/input/input418/poll' fa
iled with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/pollrate_ms' fai
led with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown input:system /sys//devices/virtual/input/input418/pollrate
_ms' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/enable_ps_sensor
' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown system:system /sys//devices/virtual/input/input418/enable_
ps_sensor' failed with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chmod 0660 /sys//devices/virtual/input/input418/set_delay_ms' fa
iled with exit code 1.
Jan 29 21:22:28 Sailfish systemd-udevd[25852]: Process '/bin/chown system:system /sys//devices/virtual/input/input418/set_del
ay_ms' failed with exit code 1.
Jan 29 21:22:28 Sailfish kernel: CAM_INFO: CAM-CRM: __cam_req_mgr_traverse: 288 Skip Frame: req: 5 not ready pd: 2 open_req count: 
1
Jan 29 21:22:28 Sailfish kernel: CPU1: update max cpu_capacity 306
Jan 29 21:22:28 Sailfish kernel: CPU4: update max cpu_capacity 1024
Jan 29 21:22:28 Sailfish kernel: CAM_INFO: CAM-CRM: __cam_req_mgr_traverse: 288 Skip Frame: req: 5 not ready pd: 2 open_req count: 
1
```

**Comment by rinigus** [comment]
That looks rather nasty. 

Camera: process could be there, but not frame grabbing in the logs. Does it happen after you reboot and don't use camera?

Re fingerprint: have you made any changes in configs regarding fingerprint? I don't think I released fp disabling, it will come with the next release of SFOS. Maybe you changed something in init files?

**Comment by pagism** [comment]
After rebooting the camera process is there, there is no frame grabbing in logs.

I cannot remember changing the fingerprint init files, i might have disabled the service in the past. 

-- 
Sent from my Jolla

**Comment by pagism** [comment]
I've disabled and masked sailfish-fp.service and also add "disabled" at the end of /vendor/etc/init/android.hardware.biometrics.fingerprint\@2.1-service.sony.rc and reboot it.

After rebooting, there are no traces of fp service or frame grabbing in journalctl.

**Comment by rinigus** [comment]
in general, /vendor and /system are for reading-only-no-touching. disabling services can be done as in https://github.com/sailfishos-sony-tama/droid-config-sony-tama-pie/commit/bcd98ad6071f318b9f04e4b147c6967e8995b6bf

**Comment by pagism** [comment]
thanks, I've reverted changes and disabled it via `/usr/libexec/droid-hybris/system/etc/init/disabled_services.rc`

**Comment by rinigus** [comment]
Recently suggested for debugging by Angelo:

* activate irq sleep debug
* check irq number
* check /sys/kernel/irq/{number}/* nodes
* check pdc-sdm845.c

**Comment by pagism** [comment]
how can be enabled that?

**Comment by rinigus** [comment]
would have to read about it. this could give some info: https://sx.ix5.org/info/post/android-kernel-suspend-debugging-and-tracing/

**Comment by rinigus** [comment]
Closing it as suspend seemed to be an expected one in flight mode.
