### ISSUE TITLE
Cellular data occasionally stops

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#35]
Once in a while (2 times per 5 days so far), cellular data just stops. Stop/start from cellular data restores the connection.

**Comment by ApostolosB** [comment]
Are you sure this is a sony devices problem and not a sailfish os one that needs to be reported and fixed by Jolla themselves. I see similar stuff -maybe not that often- with my J1 phone. In my case you need to reboot since the utilities restart doesn't fix it.

**Comment by rinigus** [comment]
No, I am not. I am now mainly keeping an eye on it. Was thinking to close it actually, as it is very rare - probably even more rare as in the first post. But let's keep it for a bit and see if it can be closed later.

On onyx (Oneplus X), I don't remember this issue. So, it does depend on adaptation and, possibly, device itself.

**Comment by ApostolosB** [comment]
Ok. In case you continue to experience this maybe it worths mention it to any of the Jolla engineers that you have contact with. If they care. There were topics for similar problems on TJC but didn't get much upvotes or replies.
Anyway. Lets see how this goes.

**Comment by pagism** [comment]
Loosing cellular connection is mainly a SFOS issue, i.e. how to maintain cellular connection efficiently. I guess baseport9 is finely tuned for xperia 10 devices, it also works for tama devices but might need further customisation? There are two SFOS services ofono/ril that deal with cellular connectivity, and there is also a "ofono logger" app that collects logs from those services, however analysing those log files requires specific knowledge or at least that's my understanding.

**Comment by rinigus** [comment]
Haven't had any issues after swapping the provider. With the previous provider, was also rather rare. Closing as cannot see it happen anymore. Open if you can reproduce it.
