### ISSUE TITLE
Flashing script not tested on Windows

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#36]
Please add reports here on whether the flashing script worked as expected here.

Remove note after the tests are done from flashing.md

**Comment by deprecated-dot** [comment]
I'm using an Xperia XZ2 (h8216). The flashing script works correctly on Windows 10 Enterprise (Version 20H2, build 19042.1348)

I have some issues with the port in general, but it flashes correctly using Windows (as well as my Gentoo primary).

I guess I can open issues for the other stuff, though I'm not sure if anyone is actively working on this.

**Comment by rinigus** [comment]
Thanks for reporting, closing it here
