### ISSUE TITLE
Haptic feedback when typing on keyboard.

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#44]
At the moment (on xz2c at least) when you type on the SFOS keyboard the haptic feedback is extremely weak or non existent.

Needs tuning because vibration works in general.

**Comment by pagism** [comment]
Haptic feedback on xz3, in general and also while typing, is good but that's my subjective opinion. I do not think SFOS provides more control, apart on/off, to adjust haptics behaviour.

**Comment by rinigus** [comment]
Same for me - I am quite happy with the current one. But I will look into how and if its possible to tune.

**Comment by ApostolosB** [comment]
I looked at some disassembly videos of the XZ2 XZ3 and XZ2C and the difference is that the first two use a linear vibration motor while the xz2c uses the classic weight on a spinning motor solution. That most likely explains why it works for you and not for my xz2c.

**Comment by pagism** [comment]
LRA vs ERM that makes a difference, I am a bit surprised xz2c is using erm.

**Comment by ApostolosB** [comment]
@pagism bean counting.

**Comment by rinigus** [comment]
@ApostolosB: there is a config file at /usr/lib/qt5/plugins/feedback/droid-vibrator-device.ini which we don't have on our device. 

For example content, see https://github.com/mer-hybris/droid-config-sony-ganges-pie/blob/master/sparse/usr/lib/qt5/plugins/feedback/droid-vibrator-device.ini

I have tried to put that file into correct location and change the settings (rebooted after a change), but cannot feel much difference. Maybe you would do. I'll ask tomorrow on the porters channel if there is somewhere I need to apply it.

**Comment by pagism** [comment]
check this https://together.jolla.com/question/75711/how-to-modifiy-vibration-strengthpattern/

**Comment by rinigus** [comment]
That would depend on the driver. We have droid-vibrator

**Comment by ApostolosB** [comment]
After adding the droid-vibrator-device.ini file and rebooting haptic feedback when typing works. So we probably need this file.
I didn't play with any of the values though but it feels ok.

**Comment by rinigus** [comment]
As it doesn't make it worse, in my opinion, for XZ2, I will add it AS-IS.

**Comment by rinigus** [comment]
@ApostolosB: please remove it on your device before you make OTA update (working on it)

**Comment by ApostolosB** [comment]
OK. BTW i haven't made any OTA update yet. I was waiting for you to give the OK.

**Comment by rinigus** [comment]
Wait a bit. OBS just started working and I am testing newer kernel with camera fixes and few other changes.

**Comment by ApostolosB** [comment]
I'll do when you say everything is ready.

**Comment by rinigus** [comment]
OTA released, see releases in this repository for notes/instructions. Please close the issue if it is fixed in the new release.

**Comment by ApostolosB** [comment]
Fixed thanks. 

PS. I'll never get used to how slow Sailfish updates. And i am used to pacman (arch) which is hell fast.

**Comment by pagism** [comment]
@rinigus, I am a bit confused, I flashed my device last Friday, yesterday, I did OTA to 3.2.1.20, release notes do not say I need to do amything more?

**Comment by rinigus** [comment]
@pagism - as you flashed from 'unofficial' image, as far as I remember, then SELinux patch is already in it. For you, all is fine after OTA

**Comment by rinigus** [comment]
@pagism : if you wish to check, just run

```
grep dbus /system/etc/selinux/*
```

If you get a hi, you are fine

**Comment by pagism** [comment]
@rinigus, yes i got a couple of them, hm a bit puzzled, because I did the upgrade before you announced it, a bit risky but the device has not data, it can be wiped off at any point.

**Comment by rinigus** [comment]
@pagism: just in case run updates again by 
```
devel-su zypper ref
devel-su zypper up
```

It will pull things that you may have missed from my last updates (maybe kernel). But I think you should be fine after that. 

Image that you flashed was already alpha1+ with few more updates available there.

**Comment by pagism** [comment]
Thanks, it got few updates
