### ISSUE TITLE
Proximity sensor gets stuck

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#47]
This one i cant rep reliably but happened twice. 

When receiving or making a call the screen blanks or doesn't show the accept decline screen. The phone rings, if you managed to answer you can hear people etc but even if the phone is away the screen flashes (show dialer dissapear).

The area i was is a bit weird when it comes to signal but i don't know if this has to do anything with it. As i said i cant rep it at home.

**Comment by rinigus** [comment]
Sounds more like proximity sensor weirdness. Keep an eye on it

**Comment by ApostolosB** [comment]
Hmmm you are probably right. I went on to test it with the CSD tool and wasn't responding. I restarted the phone and passes with flying colours. 

So probably something iffy is going on there. Will keep an eye on it.

**Comment by ApostolosB** [comment]
Could it be that we are hitting this???
https://together.jolla.com/question/193485/any-workaround-for-malfunctioning-proximity-sensor-xa2/?answer=195174#post-id-195174

Checked the journal and the only thing i saw was an undef state at one point. The time however wasn't when i experienced the problem. The files had rotated. Next time i'll check the journal when it happens.

**Comment by ApostolosB** [comment]
Ok this is definitely the proximity sensor acting up. I fired up the CSD tool -when it happened- and the sensor was stuck in covered mode.

**Comment by rinigus** [comment]
How frequent is it for you? I don't think I had this issue on XZ2.

**Comment by ApostolosB** [comment]
I cant give  an estimate on frequency. Seen it 2-3 times since i started using the phone. But what i can tell for sure is that it always happens the wrong time. :rofl:

**Comment by rinigus** [comment]
OK, that just gives some idea on how frequent we can see it and what's going on. When it will happen next time, please become root and grab the logs:

```
cd ~
# now you should be in root's home
./logs.sh proximity
```

After that, check the logs and also could send it to me. Don't forget to record the real time when it happens - so we could relate it to the timestamps in the logs.

Re wrong time: sure about it :)

**Comment by ApostolosB** [comment]
I had the phone in a stuck to covered state but i couldn't see anything related in the logs no matter what i tried (playing with the sensor etc). 

Its impossible to "catch it" the moment it gets stuck.

**Comment by rinigus** [comment]
I will have to ask about it in the porters channel. While I haven't experienced it yet, sometimes proximity does get stuck on some other devices with SFOS ports. So, there are workarounds used. For example, I think that Xperia 10 had something with proximity in its repo. Maybe that will help, I'll look into it.

**Comment by rinigus** [comment]
Try to add https://github.com/mer-hybris/droid-config-sony-ganges-pie/blob/master/sparse/etc/mce/60-proximity-sensor-ganges.conf to /etc/mce on your device. Check if it works at all and, if it does, whether it will help (presuming it will be long-term check if all works)

**Comment by ApostolosB** [comment]
I was searching about it on the internet and i found some post in a sony support forum saying it had to do with firmware. Its supposed to be fixed (on sony stock at least). The problem in the officially supported phones is also "solved" according to jolla. I asked jovirkku in TJC to ping the guy who fixed it and maybe help but no answer yet. 

I'll give that mce thing a try.

**Comment by ApostolosB** [comment]
BTW i doubt this mce thing will work. 

no /system/osso/... dir in my phone.

**Comment by rinigus** [comment]
I am not sure its a dir - its probably just a setting in mce

**Comment by ApostolosB** [comment]
I'll ask spiiroin tomorrow in the meeting if he is there. He handles stuff like that. Then i'll act accordingly.

**Comment by rinigus** [comment]
Or you could ask directly at #sailfishos-porters channel. Its also logged, btw

**Comment by ApostolosB** [comment]
After consulting spiiroin i enabled the on demand proximity with:

`mcetool --set-ps-on-demand=enabled`

i'll keep an eye on it and report back.

**Comment by rinigus** [comment]
Let's see if it helps.

**Comment by rinigus** [comment]
Note that I still haven't seen it on my device

**Comment by ApostolosB** [comment]
> Note that I still haven't seen it on my device

They might use different part and different firmware. As spiiroin explained sensors are a black box and they can't do much about it. TBH i am not a fan of the mce solution. It comes with issues that annoy me. (slowness)

Supposedly this is/was fixed in a firmware update from sony. No idea if aosp uses the same firmwares.

**Comment by rinigus** [comment]
Different part - could be. Cannot comment on how proximity is different between AOSP and stock Android. But when I checked mce solution, you can perceive the difference. Its not huge, but could be annoying.

**Comment by ApostolosB** [comment]
> But when I checked mce solution, you can perceive the difference. Its not huge, but could be annoying.

At first when i enabled it i thought i was going crazy and asked spiiroin if it affects anything. As it seems it does. I am sensitive to stuff like that -actions not happening immediately-. Even the whole tap an icon > shows the app minimized > then proceed to the full window behavior in SFOS drives me nuts.

**Comment by rinigus** [comment]
@ApostolosB : do you still have it? Or should we close the issue?

**Comment by ApostolosB** [comment]
I think its ok to close it. I havent noticed any issues -other than the slowness- since i enabled on demand. 

If something goes wrong we can reopen it.
