### ISSUE TITLE
Flashing script issue with vbmeta

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#48]
sudo ./flash.sh on linux gives you:

```
Flashing vbmeta partition...
fastboot: error: cannot load 'vbmeta': No such file or directory
```
You have to run:

`sudo fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img`

to complete the flashing.

**Comment by rinigus** [comment]
Thanks for filing it!

**Comment by MartinX3** [comment]
@rinigus AvB2 won't be supported in SailfishOS?

**Comment by rinigus** [comment]
@MartinX3 : to me it sounds like an extra headache coming with no real benefit to the user at SFOS. At least looking through https://android.googlesource.com/platform/external/avb/+/master/README.md, I think we have more important security considerations to fix on SFOS before. So, I don't see it happening any time soon.

But the flash script has to be fixed.

**Comment by pagism** [comment]
line 214 in flash.sh should be:
```
$FASTBOOTCMD --disable-verity --disable-verification flash vbmeta ${SAILFISH_IMAGE_PATH}vbmeta.img
```

**Comment by rinigus** [comment]
@pagism: thank you very much, I can see now how this error occurred!

I will publish new images as a part of the next release (SFOS 3.2.1.20) and the updated script will be a part of it. Later I will remove images from alpha release as its probably not necessary to keep them for too long.

Closing here, reopen if it still is an issue with the next release images.
