### ISSUE TITLE
DRM fix

### ISSUE THREAD

**Issue by j1warren** [sailfishos-sony-tama/main#49]
Would it be possible to rewrite a DRM fix (https://www.xperifix.com) for XZ2*?

I think it applies on boot in initrd, probably by mounting some saved TA partition over a real one.
So AOSP blob will think the phone is still locked and there's no need to cripple the camera features.

**Comment by ApostolosB** [comment]
Someone posted a link -in a place that i cant find now- that after android pie the camera isn't affected by unlocking the bootloader. 

However. The camera needs to be optimized. And this is an ongoing process.

**Comment by j1warren** [comment]
AFAIR it was said that since pie unlocking BL erases less proprietary keys than before, but it still disables some bits.

**Comment by ApostolosB** [comment]
Anyway. I wouldn't expect something like this to come from this project. There are many stuff to fix in SFOS and the port in general.

**Comment by rinigus** [comment]
AOSP uses different camera implementation and there is an ongoing major work on it. At some point, we will use that updated driver on SFOS as well. That's at least a plan right now.

As for other features disabled by TA wipe, you will have to check out at XDA. To make it properly work, it has to be done on AOSP side, if any. But I don't expect it to be done or be high priority. 

Closing over here as its out of scope. But we will work on improving the port :)

**Comment by MartinX3** [comment]
And DRM is only part of the stock ROM.
SailfishOS uses the SODP.
Sony Open Device Project is from Sony, but has nothing to do with the stock firmware and its DRM. :)

The camera is just work in progress and will receive updates until the quality becomes good.
