### ISSUE TITLE
Charging LED behavior

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#50]
The charging LED doesn't work reliably. It sometimes blinks slowly (as normal in J1) and other times stays white all the time.

**Comment by rinigus** [comment]
In my understanding, LED during charging is 

- staying white to indicate charging, unless condition below is true
- blinks if you have new notification

For me, that is expected and the same as was on 1+X. Let me know if the pattern indicated by me is correct and would explain your results.

**Comment by ApostolosB** [comment]
When charging (usb plugged in) the LED stays white. When the battery reaches 100% the LED blinks white. That is the behavior i would expect. And i saw it blink white when the battery reached 100% at some point. Also on the J1 it also turned the screen on to indicate that it had reached 100%.

New notifications blink but have different colours. Email yellow, SMS blue, unanswered call green.

**Comment by rinigus** [comment]
I don't think I have seen it blink at 100%, but I maybe didn't notice. Will check on my side

**Comment by ApostolosB** [comment]
OK. After some more observations. When the phone shows 100% the led doesn't start blinking immediately. If you let the phone on the charger it will start to blink after some minutes. (10-20 maybe)

**Comment by rinigus** [comment]
I presume its something to do with "smart battery charging" that Tama has. Its somewhat different from others and can suspend while charging, for example. As such, I think this behavior is OK. Don't know whether it was also 10-20 min in my case, I saw it blinking and it was 100% charged.

For me, that all seems to be fine and I would suggest to close it as an issue.

**Comment by ApostolosB** [comment]
Yep.
