### ISSUE TITLE
Apps take a long time to start or don't at all (sometimes)

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#51]
Seen this in a few occasions. Every now and then apps (ie browser, sailotp from the store) stay in the cover view with the spinning circle and either take some time to move to full screen view or disappear. 

I run a free -h in the terminal after it happened and didn't notice anything weird -at least to my untrained eye.

**Comment by rinigus** [comment]
Hard to say, maybe RAM allocation related. I will ask few questions around regarding it

**Comment by pagism** [comment]
I got into the same problem while testing battery consumption, i.e. everything is off, and waking up phone every hour to open terminal app and log stats.
in few cases, starting the terminal app takes some time, and in my last "logging" attempt the terminal app took too long to start it disappeared from the app tray. Second attempt to start the terminal was fast.

**Comment by ApostolosB** [comment]
One note on the behavior. When an app gets stuck if you open another app, minimize it, and tap the stuck app it usually starts.

Just writing this in case it helps finding the cause of the issue.

**Comment by pagism** [comment]
I've encountered the same issue several times, the system is not busy, there is plenty of ram available, is there any way to monitor what is causing that?
e.g. I had by chance an ssh session open, and while starting the browser spinning, I run free, w, and top
```
[nemo@Sailfish Documents]$ free
              total        used        free      shared  buff/cache   available
Mem:        3765028     1757500     1081268       32332      926260     2341380
Swap:       1048572           0     1048572
[nemo@Sailfish Documents]$ w
 11:03:45 up 10:26,  1 user,  load average: 2.18, 2.39, 2.67
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
top - 11:04:02 up 10:26,  1 user,  load average: 2.25, 2.40, 2.68
Tasks: 700 total,   1 running, 699 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.4 us, 25.8 sy,  0.2 ni, 67.2 id,  0.1 wa,  0.6 hi,  0.7 si,  0.0 st
MiB Mem :   3676.8 total,   1056.6 free,   1715.1 used,    905.0 buff/cache
MiB Swap:   1024.0 total,   1024.0 free,      0.0 used.   2287.8 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND        
25090 root      20   0       0      0      0 S   2.0   0.0   2:43.19 kworker/u16:17 
31320 root      20   0       0      0      0 S   1.7   0.0   0:42.66 kworker/u16:15 
31670 nemo      20   0    6972   3236   2192 R   1.0   0.1   0:00.25 top            
30351 root      20   0       0      0      0 S   0.5   0.0   0:00.07 kworker/u16:29 
  692 root      20   0    4508   2524   2096 S   0.4   0.1   2:17.69 systemd-journ+ 
  720 root      20   0   11952   3696   2448 S   0.3   0.1   2:11.42 systemd-udevd  
30148 root      20   0       0      0      0 S   0.2   0.0   0:00.09 kworker/u16:12 
    7 root      -2   0       0      0      0 S   0.2   0.0   0:25.72 rcu_preempt    
   15 root      rt   0       0      0      0 S   0.2   0.0   0:38.90 migration/0    
   28 root      rt   0       0      0      0 S   0.2   0.0   0:29.21 migration/2    
   46 root      rt   0       0      0      0 S   0.2   0.0   0:20.54 migration/4    
 3190 root      20   0   20944   8892   7780 S   0.2   0.2   1:14.77 mce            
 3428 root      20   0   32116   7684   6336 S   0.2   0.2   1:02.37 connmand       
 6497 root      20   0       0      0      0 S   0.2   0.0   0:04.56 kworker/2:6    
    8 root      -2   0       0      0      0 S   0.1   0.0   0:13.53 rcu_sched      
   11 root      20   0       0      0      0 S   0.1   0.0   0:06.78 rcuos/0        
   18 root      20   0       0      0      0 S   0.1   0.0   0:20.87 cpuhp/1        
   27 root      20   0       0      0      0 S   0.1   0.0   0:14.44 cpuhp/2        
   33 root      20   0       0      0      0 S   0.1   0.0   0:11.84 rcuop/2        
   34 root      20   0       0      0      0 S   0.1   0.0   0:05.02 rcuos/2 
```
when top started there was a kworker process at 50% cpu

**Comment by rinigus** [comment]
I don't know and nor have any theory to test regarding this slow start and sometimes non-starting. You could try to look into logs (journalctl) and see whether there is some anomaly at that time. As for RAM allocation mysteries, I will still have to ask around - looks like in Jan 2020 though as I will have rather limited amount of time before that.

**Comment by pagism** [comment]
No worries, I've attached the output of journalctl and dmesg logs for a reference.

[journalctl.log](https://github.com/sailfishos-sony-tama/main/files/4006989/journalctl.log)
[dmesg.log](https://github.com/sailfishos-sony-tama/main/files/4006990/dmesg.log)

**Comment by rinigus** [comment]
For reference, indicate also time when it happened. As going through MBs of logs without a time reference makes it rather difficult. :)

**Comment by pagism** [comment]
deleted previous comment and renamed logs to include timestamp and model

[journalctl_xz3_28_12_2019.log](https://github.com/sailfishos-sony-tama/main/files/4007008/journalctl_xz3_28_12_2019.log)
[dmesg_xz3_28_12_2019.log](https://github.com/sailfishos-sony-tama/main/files/4007009/dmesg_xz3_28_12_2019.log)

**Comment by rinigus** [comment]
But we need also to know when app starting issue happened, as precisely as possible.

**Comment by ApostolosB** [comment]
https://together.jolla.com/question/219961/xa2-bad-memory-handling-lots-of-oom-killing/

I am putting this here also since it seems to be similar. Its weird that it seems to happen with phones that have quite a bit of ram and ie my J1 never had it.

**Comment by ApostolosB** [comment]
Something weird happened today. I went to start an app and the phone interface "froze". With a long press at the power button i managed to get it to shutdown. 

Could it be the case we have some memory handling issues or leaks?? With free -h i've noticed the free memory dropping from 2.2G (after a reboot) to 1G after a few days of uptime.

**Comment by pagism** [comment]
three comments:
- I experience on regular basis apps failing to start with first tap, usually 2nd attempt apps start fast, also some times it takes long time to wake up screen, e.g. 2+ sec
- a week ago the phone could not wake up, instead the spinning circle was displayed, long scroll from top the settings menu was accessible, I was also able to take pictures, but nothing more as the device was locked. Unfortunately remote access was disabled and the only option i had to regain access was to reboot the phone.
- free memory is not always a safe indication on its own.

**Comment by rinigus** [comment]
Frozen phone: you may try to restart lipstick. I think it was double click on power button - not a simple solution but may work. I have used it once in a while.

Apps not starting - occasionally happens to me as well. But mostly due to the bugs in the programs that I develop. Will have to catch logs when its something else.

And with free memory on Tama - will have to look into it.

**Comment by ApostolosB** [comment]
> Something weird happened today. I went to start an app and the phone interface "froze". With a long press at the power button i managed to get it to shutdown.
> 
> Could it be the case we have some memory handling issues or leaks?? With free -h i've noticed the free memory dropping from 2.2G (after a reboot) to 1G after a few days of uptime.

Ok. So i can confirm this is something that happens. The phone froze again after i tried to open an app. Had to reboot. Noticed the same thing with memory again. free memory goes down and used memory goes up.

So most likely we have a bug/problem. And is happening after a few days (9 maybe) without a reboot.

**Comment by ApostolosB** [comment]
@rinigus 

Should i open a new issue on the frozen phone or keep it here. 
The phone freezes and if you double click the power button its just a red LED blinking.
Needs restart after that. Its not recoverable.

**Comment by rinigus** [comment]
Hard to say, I don't know. I haven't experienced none of the freezing like that. Inability to start apps is rare and usually limited to a specific ones (matrix client, for example). So, gonna be hard to fix is I am not able to reproduce it...

**Comment by ApostolosB** [comment]
How often do you reboot your phone??

Also which matrix client do you use. I thought there weren't any full featured for SFOS yet.

**Comment by rinigus** [comment]
Good question. Looking on stats, longest uptime has been 8 days, usually up to 4. Each time for reboot is different, but its usually development enforced (kernels, libhybris, some other vital component needs refresh).

Re matrix: using harbour-matrix, as compiled by r0kk3rz in build merproject OBS. not perfect, but OK

**Comment by pagism** [comment]
There are a couple of tjc reports eg

https://together.jolla.com/question/22783/bug-green-led-blinking-phone-yammed/?answer=29371#post-id-29371

**Comment by ApostolosB** [comment]
Things i observed.

I run:
`ps -o pid,user,%mem,command ax | sort -b -k3`

The process that consumes most of the memory -from restart- is lipstick and seems to be going up as days pass without a reboot. So its either lipstick that causes the stuck interface issue (although it has memory and swap space to do its stuff) or something that doesn't gets listed with the above command.

**Comment by rinigus** [comment]
Interesting. How large is Lipstick memory consumption for you? For me, RSS is about 150MB, which is not that much. Uptime 5 days

**Comment by ApostolosB** [comment]
I 've only seen the percentages from the command above. starts at 3.7 and goes up to 4.3 as days go by.

**Comment by rinigus** [comment]
That's similar over here. Don't think 4% would be causing OOM killer

**Comment by ApostolosB** [comment]
And i suspect neither the freezes also. So its probably something else.

**Comment by ApostolosB** [comment]
@rinigus one thing though. When an app is stuck at the minimized state (before it goes full screen) it -usually- goes to full screen if you tap it again. So it might not be a memory problem but something that happens before the transition to full sceen. What i have no idea.

**Comment by pagism** [comment]
Correct, and if you do not wait for the app to be killed, you can starg a second instane of tge app without issues. Sometimes i notice a similar behaviour waking up the screen, it takes a couple of seconds to wake up.

My feeling is that the app somehow has a very slow start up and get killed by another monitoring process  as it's slow to respond? Very occasionaly similar behaviour is observable in other officially supported devices.

-- 
Sent from my Jolla

**Comment by rinigus** [comment]
That I have seen (clicking on minipage with delayed start), mainly on Flatpak apps. Although nothing alarming found in the logs. Could be some Lipstick interaction with an app starting slowly for some reason. Although, Flatpak Runner is a small app by itself...

**Comment by ApostolosB** [comment]
Most likely -or definately- lipstick needs a complete overhaul. Comply to the latest protocol and fix performance issues, if those are caused by it. Its not reasonable to have SFOS running on phones that can run fortnite and SFOS to have issues.

**Comment by rinigus** [comment]
This is not limited to Lipstick. I have just had Flatpak Runner started and Angelfish failing to do so. After reboot, all was fine.

Didn't debug it further as I was finishing few things with Angelfish development and didn't have time for it. But in this respect, Lipstick could be just a "messenger"

**Comment by ApostolosB** [comment]
@rinigus i think this needs to be brought up in a mailing list.  :man_shrugging:

**Comment by rinigus** [comment]
Maybe. But I would prefer to be better prepared before asking for help. Will grab some logs next time, silly that I didn't do it this time.

**Comment by ApostolosB** [comment]
After observing this for a while i am sure what eats the memory isn't something that sill show up with the ps command above.

**Comment by rinigus** [comment]
I have the similar feeling, based on collectd data. Something doesn't add up, but have to figure out what.

**Comment by ApostolosB** [comment]
@rinigus can you test something if you have time. It seems to me that things get worst in regards to memory (and eventual freeze) when streaming audio to a device. 

Might worth trying if possible.

**Comment by ApostolosB** [comment]
Someone suggested today (in the meeting) that i should test with starting the apps from the terminal and see if one gets stuck. After a lot of attempts nothing out of the ordinary happened. All apps started normally. So something happens whey you start the apps from the app tray.

Just mentioning this here. If someone else can test feel free and mention your results.

**Comment by pagism** [comment]
I doubt it will be observed from a terminal, the only way to get info is indirectly from logs?  hopefully upgrade to 3.3 will help? 

-- 
Sent from my Jolla

**Comment by rinigus** [comment]
Terminal bypasses Sailfish boosters. I have seen on my earlier devices that sometimes my own app doesn't start from GUI but runs fine from terminal. So, I doubt as well that the terminal will help much.

As for update, will work on it when we get target at OBS - it's still absent so far. But it will come for sure.

**Comment by ApostolosB** [comment]
is there any way to log what is going on with the boosters??

**Comment by pagism** [comment]
I have not noticed long app start times since 3.3 upgrade, and also I have the feeling battery consumption is better

**Comment by ApostolosB** [comment]
@pagism i just logged in to comment on that. I haven't noticed the issue in 3.3 and was about to ask if anyone is experiencing the same.

**Comment by rinigus** [comment]
We have just rebooted recently, let's wait whether it will resurface with time. But there were plenty of kernel updates included this time as we had a longer break between releases. Let's hope that it got resolved by great work of Sony AOSP team that they do on the kernels.

**Comment by ApostolosB** [comment]
I am closing this since it seems that the issue with apps taking a long time to start be a thing of the past. I had a reboot or two nothing "extreme" like the previous release. 

There still seems to be something that makes the free memory reduce over time (checking with free -h) but overall the phone is much more stable

In case anyone still sees the issues described here feel free to reopen it.
