### ISSUE TITLE
terminal app keyboard is sluggish

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#57]
i am not sure if this issue belongs here, but the default finger terminal keyboard is awful on xz3, it's impossible to type without errors on every second keypress.

the sfos keyboard, eg notes, is fine, more responsive.

**Comment by ApostolosB** [comment]
That is a fingerterm issue. There is [ToeTerm](https://openrepos.net/content/direc85/toeterm) on Openrepos but i doubt the keyboard is less cramped. (judging from screenshots).

**Comment by rinigus** [comment]
Don't think it belongs to the port as such. Maybe its related to your battery issue, as something is going on on your device leading to high battery consumption.

Closing it here. If after fixing battery its still sluggish, open it with terminal developers please - assuming that everything else works properly.

**Comment by pagism** [comment]
it is not related with battery consumption, finger terminal has it's own keyboard so it might be an issue for terminal developers, or simply an app configuration issue.

**Comment by rinigus** [comment]
I was making comment regarding 'sluggish' aspect. As for keys being jammed - I frequently use it in landscape mode to have some space. Will have to test ToeTerm again, haven't done it for a while. Feel free to file it with the devs of the terminal app - no idea who they are, though
