### ISSUE TITLE
font, icons scaling for xz3 screen

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#60]
xz3 screen resolution, although 18:9 ratio, is 1440x2880 pixels, compared to XZ2 variants which are 1080x2160. Changing text size in "settings/display/text size" is partially fixing the problem. 

ps not sure if this is an upstream issue?

![Screenshot_20191226_001](https://user-images.githubusercontent.com/59111727/71517267-298c5900-28a5-11ea-92af-ef53327f5e59.png)

**Comment by rinigus** [comment]
Its unfortunate limitation of currently available pixel ratios (2.0 is a max): https://github.com/sailfishos-sony-tama/droid-config-sony-tama-pie/blob/master/rpm/header-h8416.inc#L5

Its the same problem for XZ2c, which would have benefited from higher aspect ratio icons available.

Please open issue at TJC and keep it open here. I believe other devices could be approaching the same limit

**Comment by pagism** [comment]
I opened an issue at TJC, thanks.

**Comment by rinigus** [comment]
Closing it over here as I don't think we can do something on our side. Please ping the issue at TJC, ask at scheduled meetings of community.
