### ISSUE TITLE
restricted harbour store app access

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#61]
is availability of harbour store apps somehow restricted for tama devices? e.g. search for aida64 or sidudict does not list these apps.

**Comment by rinigus** [comment]
it shouldn't be. what is your device specifically (single or dual xz3?). I can access these apps. Let me know your device model as in `ssu s` and I can ping on the porters channel

**Comment by pagism** [comment]
xz3 single sim
Device registration status: not registered
Device model: Xperia XZ3 (h8416 / h8416)
Device UIDRelease: 3.2.1.20
Domain: salesBrand: Jolla

**Comment by ljo** [comment]
I also got this for some apps, but since it only were some odd ones e.g. rpncalc, I just put it in cache problem category at that time (Dec 6th).

**Comment by rinigus** [comment]
I can see that I asked for 

Xperia XZ2 (h8216 / h8216)
Xperia XZ3 (h9436 / h9436)
Xperia XZ2 (h8266 / h8266)

h8416 was not requested yet. To request it, I need you check if

- ssu s returns IMEI as a device id
- that IMEI is shown correctly in Settings/About product
- IMEI is the same as was on your box or in Android

As soon as this is confirmed, I can ask for full access.

**Comment by rinigus** [comment]
PS: @ljo: If your phone was in the device list above, please let me know. I will have to notify about problems then

**Comment by pagism** [comment]
I can confirm that the Device UID in `ssu s` is the same with the SailfishOS Settings/About page, and the same as the android one.
```
[nemo@Sailfish ~]$ ssu s
WARNING: ssu.ini does not seem to be writable. Setting values might not work.
Device registration status: not registered
Device model: Xperia XZ3 (h8416 / h8416)
Device UID: xxxx
Release: 3.2.1.20
Domain: sales
Brand: Jolla
```
thanks

**Comment by rinigus** [comment]
Requested. Now we will have to wait

**Comment by rinigus** [comment]
@pagism : your device has been added, please try again

**Comment by rinigus** [comment]
PS: close the issue if it works

**Comment by pagism** [comment]
thank you  i just checked it, it works !
