### ISSUE TITLE
SIM card not detected

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#62]
My XZ3 was working fine with SIM  card in, the last time I wanted to use an SD card to restore a modified backup tar from XA2 to XZ3. The modified backup tar had only Notes and Calendar contents.

It seemed to work fine, but later I noticed no sim card was detected, I run few reboots swapping sim cards, the XZ3 seems to ignore them. I've recreated /var/lib/ofono and compare it with my XA2, they are almost identical.

```
[root@Sailfish lib]# journalctl -u ofono
-- Logs begin at Thu 2020-01-09 14:03:22 GMT, end at Thu 2020-01-09 14:07:50 GMT. --
Jan 09 14:05:37 Sailfish systemd[1]: Stopping Telephony service...
Jan 09 14:05:37 Sailfish ofonod[25865]: Terminating
Jan 09 14:05:37 Sailfish ofonod[25865]: SMS History Remove for modem: 0x77ac30
Jan 09 14:05:37 Sailfish ofonod[25865]: Exit
Jan 09 14:05:37 Sailfish systemd[1]: Stopped Telephony service.
Jan 09 14:07:32 Sailfish systemd[1]: Starting Telephony service...
Jan 09 14:07:32 Sailfish ofonod[31970]: oFono version 1.22
Jan 09 14:07:32 Sailfish systemd[1]: Started Telephony service.
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding udev hardware detection
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Novatel modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Sierra modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding ZTE modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Icera modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Huawei modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Calypso modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding MBM modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Telit modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding HSO modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Infineon modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding STE modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Dialup modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Hands-Free Profile Driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding SpeedUp modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Phone Simulator driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding CDMA AT modem driver
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding External Hands-Free Profile Plugin
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding Dial-up Networking Profile Plugins
Jan 09 14:07:32 Sailfish ofonod[31970]: Excluding CDMA provisioning Plugin
Jan 09 14:07:32 Sailfish ofonod[31970]: Initializing RIL binder transport plugin.
Jan 09 14:07:32 Sailfish ofonod[31970]: Register Profile interface failed: /bluetooth/profile/hfp_ag
Jan 09 14:07:32 Sailfish ofonod[31970]: [gbinder-radio] Connected to android.hardware.radio@1.0::IRadio/slot1
Jan 09 14:07:32 Sailfish ofonod[31970]: slot1 version 100
Jan 09 14:07:32 Sailfish ofonod[31970]: SIM card OK
Jan 09 14:07:32 Sailfish ofonod[31970]: Requested file structure differs from SIM: 6fb7
Jan 09 14:07:32 Sailfish ofonod[31970]: SMS History Probe for modem: 0x4e66c8
Jan 09 14:07:32 Sailfish ofonod[31970]: Registered interface org.ofono.NetworkTime, path /ril_0
Jan 09 14:07:32 Sailfish ofonod[31970]: nw select automatic
Jan 09 14:07:32 Sailfish ofonod[31970]: data reg changed 0 -> 2 (searching), attached 0
```
and 

```
[root@Sailfish lib]# systemctl status ofono.service
● ofono.service - Telephony service
   Loaded: loaded (/lib/systemd/system/ofono.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-01-09 14:07:32 GMT; 24min ago
 Main PID: 31970 (ofonod)
   CGroup: /system.slice/ofono.service
           └─31970 /usr/sbin/ofonod -n --nobacktrace --noplugin=,he910,dun_gw_bluez5,hfp_bluez5,cdma_provision,isimodem,n900,u8500,qmimod...

Jan 09 14:19:41 Sailfish ofonod[31970]:   Password: ''
Jan 09 14:19:41 Sailfish ofonod[31970]: Name: 'Giffgaff MMS'
Jan 09 14:19:41 Sailfish ofonod[31970]:   APN: 'giffgaff.com'
Jan 09 14:19:41 Sailfish ofonod[31970]:   Type: OFONO_GPRS_CONTEXT_TYPE_MMS
Jan 09 14:19:41 Sailfish ofonod[31970]:   Username: 'giffgaff'
Jan 09 14:19:41 Sailfish ofonod[31970]:   Password: ''
Jan 09 14:23:48 Sailfish ofonod[31970]: Requested file structure differs from SIM: 6fb7
Jan 09 14:24:48 Sailfish ofonod[31970]: registration failed, ril result 2
Jan 09 14:24:48 Sailfish ofonod[31970]: Unable to read mailbox identifies from SIM
Jan 09 14:24:49 Sailfish ofonod[31970]: export_entries_one_storage_cb with ME failed
```
I am now running out of options, I will try sfos reset, and possibly reflash android?

**Comment by rinigus** [comment]
I am blank on it. No idea what does the backup restore do. I would assume that its mainly about /home/nemo and shouldn't touch the rest. Personally, I am using rsync for these tasks. 

If you are willing to reflash, that would give an indication of what's wrong. If reflash of SFOS will not be sufficient, then we will have to test Android as well to make sure its not hardware issue.

**Comment by pagism** [comment]
I doubt restore did that, anyway, it seems I have to do a re-flash. Is there any procedure, or any logs that can be collected?

**Comment by ljo** [comment]
This once or twice happened for me too. But for some reason turning off the wifi made the sim/phone functionality recover. (I know it sounds wonky)

**Comment by rinigus** [comment]
I have seen it with 1+X SFOS port and might have had it in the beginning of the port as well, but not as bad as described here.

Re logs: let's switch off wifi (@ljo suggestion), boot into SFOS and see if the card appears. If not, shutdown or reboot. After reboot, you will have set of logs at /root/*shutdown* that would be good to keep. Get them off device (ssh wifi?) and see if there is something strange in logcat. If nothing jumps out, we should probably reflash.

Don't paste full logs here  as you may disclose your IMEI or some private data. If needed its better to send them by email.

**Comment by pagism** [comment]
I tried all that for nth time, not working. I've also took logs from /root. The system can read SIM card /var/lib/ofono correctly, in comparison to XA2 those contents are almost identical.

CSD tool shows SIM card PASS

**Comment by rinigus** [comment]
Just to be sure: if you put that SIM card into another phone, all works. And you have tested it after the issue started?

As we had, by chance, one of the operators having problems with the service...

**Comment by pagism** [comment]
yes, I tested that before started the issue, I've also tested another sim (data only) and it does not work.

**Comment by rinigus** [comment]
So, CSD passed SIM card test. Does it show whether its present? If present, does it show card identifier?

**Comment by pagism** [comment]
yes it shows card identifier, subscriber numbers: N/A

**Comment by rinigus** [comment]
I can try to ask around tomorrow evening or Saturday - then I will have to get logs by email - or you could try to flash SFOS, and if it fails, AOSP to proceed faster. Its late over here ...

**Comment by pagism** [comment]
thanks for your help, I can reset/flash the phone at any time, if you think it's worth investigating the problem more I can wait and send you the logs, just let me know. thanks again.

**Comment by rinigus** [comment]
Maybe we should flash to be sure its not hardware/firmware issue. So, try to 

- flash SFOS again
- if SFOS doesn't work, flash AOSP9
- if AOSP9 doesn't work, flash stock Android 9 (not 10). You can use Newflasher for it from Linux or Sony's tool

Let me know how it goes. Keep the used backup file in case if we need to test whether we can reproduce the issue.

**Comment by rinigus** [comment]
In addition, make screenshot from CSD with SIM test - for the record. In case if we need it.

**Comment by pagism** [comment]
OK i will try later today, what is the used backup file? Or how to get it?
 
> Let me know how it goes. Keep the used backup file in case if we need to test whether we can reproduce the issue

**Comment by rinigus** [comment]
The one you used to restore Calendar, as in the original message

**Comment by pagism** [comment]
it started working again this morning, i.e. i will avoid re-flashing or even worse some h/w damage, phew!

After turning on/off, swapping sim cards, restarting ofono.service, switched to "Preferred 3G" since yesterday afternoon,  i removed the sim card and switched off the phone last night. This morning I put back the sim card and turned on the phone, after booting still no cellular connection shown, not impressed. 5min later I turned the screen on and a full 3G signal bar was shown, automagically.

I still do not know what caused the problem but I will close this issue here. I still have boot and shutdown logs if anyone is interested, thanks for your support.

**Comment by pagism** [comment]
it seems that I closed the issue a bit early, cellular connection has automagically disappeared again, the phone was on all time, no reboot or sim card swapping.

**Comment by rinigus** [comment]
That is all strange. Reopening.

**Comment by pagism** [comment]
we might have to rename the issue to cellular connection dropped, there are many similar references in TJC. The sim card is detected and read correctly, so it might be the old SF connectivity issue?

There is a harbour ofono logger app that collects logs for telephony troubleshooting which can be sent directly to Jolla, but I doubt if they are interested much for an unofficial device. Re-flashing SFOS might still be an option.

**Comment by rinigus** [comment]
Could be that issue. What I have seen is #35 , frequency maybe once a week. But its not full blown disconnect - I can probably still call. And has a simple cure - press mobile network icon twice to disable/reenable. Your case seems to way more problematic.

Maybe will need to reflash if you cannot restore it.

**Comment by pagism** [comment]
I think we should close this issue, as sim card detection and cellular network connections are not the same, besides the actual problem is cellular network connection dropouts.
For sim card detection the test is simple, csd tool sim test pass.

**Comment by rinigus** [comment]
Agreed. Closing, open another one or use #35 if appropriate
