### ISSUE TITLE
No input after wake up.

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#63]
Happened twice thus far -rare occasion- but yeah.

Wake the phone with the button and you get no input. Pressing the button and waking it up again solves it.

**Comment by rinigus** [comment]
Do you mean that touch was not working?

**Comment by ApostolosB** [comment]
> Do you mean that touch was not working?

Yep.

**Comment by rinigus** [comment]
Have seen it on 3.4 on XZ2c. Not sure what to do about it, though. Not on XZ2 yet

**Comment by ApostolosB** [comment]
Not yet but its a rare bug in general. I'll see how it goes in a few days/wweks of use.

**Comment by ApostolosB** [comment]
Bad news. I got it today. So apparently its still here.

**Comment by rinigus** [comment]
Well, not too bad news, all things considered. Minor annoyance maybe :) . I am not planning to investigate it. Let's see if it will still be there after we move to AOSP10 and 64 bit. Hopefully that will come one day, at least it is planned

**Comment by ApostolosB** [comment]
Oh no need to go into it. As i said its rare.

AOSP 10 would be awesome to have.

**Comment by ApostolosB** [comment]
This doesn't seem to happen with hybris10 so i am closing this. If i notice anything wrong i'll file another issue.

**Comment by rinigus** [comment]
Thanks!
