### ISSUE TITLE
Flashing script fails for H8324

### ISSUE THREAD

**Issue by pstassen** [sailfishos-sony-tama/main#64]
Hi,

I don't know if this is more a fastboot issue or an issue with the script. I've been struggling to unlock the bootloader on my H8324 (XZ2 Compact Dual SIM) and now the flashing script returns the following error:

```
Detected Linux
Searching device to flash..
Found 1 devices: BH90375BBZ 
Fastboot command: fastboot -s BH90375BBZ  
Flashing boot partition..
Sending 'boot' (20360 KB)                          FAILED (remote: 'unknown command')
Finished. Total time: 0.005s
```

Now I tried to flash the different partitions using `fastboot flash`. It seems to send the files to the phone

```
$ sudo fastboot flash dtbo dtbo.img --skip-reboot
< waiting for any device >
Sending 'dtbo' (8192 KB)                           OKAY [  0.237s]
Writing 'dtbo'                                     OKAY [  0.150s]
Finished. Total time: 0.394s
```
But now I'm in a boot loop.

**Comment by pstassen** [comment]
Just reflashed all partitions using the command line and the phone booted into Sailfish OS. I could not keep the device smartphone connected to the computer and had to run each command before plugging the phone holding the "Volume up"-button. I would guess this is a fastboot issue because it is pretty old (my version of android-tools is 20180828gitc7815d675 on Fedora 30 "updates" repository). Don't know if it's been anything new since then...

**Comment by rinigus** [comment]
It could also be issue with USB connection if you used USB3 port on PC, for example. Great that it got resolved
