### ISSUE TITLE
There is no Android app support

### ISSUE THREAD

**Issue by Gouster4** [sailfishos-sony-tama/main#68]
Did you tryed implementing anbox arm64?

**Comment by Gouster4** [comment]
https://github.com/anbox
https://github.com/Sailfish-On-Vince/anbox

**Comment by rinigus** [comment]
No, I haven't tried to setup anbox. I don't plan to do so either. But Anbox is open source software and if someone wishes to work on it, please do so.

**Comment by rinigus** [comment]
Closing as stale. Absence of Android support is clearly stated in README.
