### ISSUE TITLE
Test if QPA_HWC_IDLE_TIME and/or QPA_HWC_BUFFER_COUNT improves responsiveness

### ISSUE THREAD

**Issue by rinigus** [sailfishos-sony-tama/main#69]
As suggested during the meeting, we need to test whether QPA_HWC_IDLE_TIME and QPA_HWC_BUFFER_COUNT ? https://github.com/mer-hybris/hadk-faq#id26

@ApostolosB, please look into it as you feel some choppiness

**Comment by ApostolosB** [comment]
Tried it and didn't seem to make a difference. It somehow felt i was seeing more red lines. And choppiness on the media player.

**Comment by ApostolosB** [comment]
To be clear i tried each one separately and both and didn't see an improvement.

**Comment by rinigus** [comment]
Just checking: did you reboot after the changes during the test?

**Comment by ApostolosB** [comment]
Errmmm. I restarted user@100000 as mentioned in the guide. No reboots.

**Comment by rinigus** [comment]
If its sufficient according to the guide then it should be fine. Closing, as tests done and no improvement found
