### ISSUE TITLE
MTP connection fails with USB3 drivers

### ISSUE THREAD

**Issue by Giggeli** [sailfishos-sony-tama/main#70]
If XHCI USB drivers are enabled from bios, windows and linux will be unable to access the phone via MTP protocol. EHCI drivers just works. Also confirmed this issue by second computer.

**Comment by rinigus** [comment]
Do you know whether it works on Sony Android? on other Sailfish devices?

**Comment by Giggeli** [comment]
Yes I have been tested that before flashed as also moved some files to xz3 succesfully.

**Comment by rinigus** [comment]
As USB3 works for me on Linux for MTP, closing this as stale. We have switched bases meanwhile and it probably has to be reevaluated if it is still true
