### ISSUE TITLE
lack of BTRFS filesystem 

### ISSUE THREAD

**Issue by Giggeli** [sailfishos-sony-tama/main#71]
Port lacks btrfs filesystem support. Is it intended to drop it from kernel?  Its not listed in proc/filesystems.

**Comment by rinigus** [comment]
Yes, it's intended. I had issues with booting kernels containing many filesystems. At some point, probably as a part of kernel update to 4.14, I can look into it. But don't expect such update in the next couple of months.

**Comment by rinigus** [comment]
Fixed in AOSP10 based build

**Comment by MartinX3** [comment]
Is it possible to add it to SODP?
Formatting the sdcard to btrfs should be an improvement over ext4 (with automatic scrubbing and defragmentation).

**Comment by rinigus** [comment]
On kernel side, sure thing (see config at https://github.com/sailfishos-sony-tama/android_kernel_sony_msm/blob/hybris-10.0-4.14/arch/arm64/configs/aosp_tama_akari_defconfig#L946, maybe more is needed).

But I don't know how well does SODP would support system tools to use it.
