### ISSUE TITLE
[META] Switch to 4.14 kernel

### ISSUE THREAD

**Issue by Thaodan** [sailfishos-sony-tama/main#79]
This script tracks my idea to switch to a 4.14 based kernel and related issues.
Switching to a 4.14 based kerne likely fixes #1

**Comment by Thaodan** [comment]
Depends on:
- #80 
- #81 
- #82

**Comment by rinigus** [comment]
@Thaodan : so, do you propose to switch with AOSP9 base to 4.14? I will have to ask from Sony's devs how future-proof it is and whether new blobs may support it.

**Comment by Thaodan** [comment]
If I understand it correctly it was tested by Sony devs?

**Comment by rinigus** [comment]
I don't know. Will have to ask

**Comment by rinigus** [comment]
May require also switch to clang: https://github.com/sonyxperiadev/kernel-sony-msm-4.14-common/commit/39779cef3700941436d7d8c448186236dff11f71

**Comment by MartinX3** [comment]
Internal some sodp team member use the GCC, but not the one bundled/removed from aosp.
They use the best one as far as I know.

**Comment by Thaodan** [comment]
The kernel builds just fine with GCC.

**Comment by rinigus** [comment]
@Thaodan and @MartinX3 : sounds like I will have to try it soonish, as there is an interest :) . As for GCC/Clang - it may also affect interaction with the blobs.

**Comment by Thaodan** [comment]
At least when I run my device (kumano) with AOSP I had no side interaction with the kernel being build by gcc regarding blobs.

**Comment by rinigus** [comment]
As described in https://github.com/sailfishos-sony-tama/main/issues/81#issuecomment-660619965, it is early and it is not expected to work on AOSP9.

I suggest to close all 4.14 related issues and deal with it when AOSP10 based ports will be available. Then we should port Tama to AOSP10 and switch over to that port.

**Comment by rinigus** [comment]
@Thaodan: as I have separate test device, I will test if it works (4.14+AOSP9). If it doesn't, we will have to see how to get AOSP10 base working for SFOS. Timing is not clear for the latter, though

**Comment by rinigus** [comment]
I have compiled 4.14 (with gcc for now) and I can boot into recovery with 4.14 blobs. However, rndis network seems not to be working then as I don't get any connection established. @Thaodan, as far as I could see, your changes in config were carried over and all is fine there.

Haven't tried to fire full SFOS yet, would like to get recovery working first. Maybe some other day.

**Comment by rinigus** [comment]
Is a part of AOSP10 based porting effort. Is switched over there. Closing
