### ISSUE TITLE
Adjust kernel 4.14 defconfig for hybris on tama

### ISSUE THREAD

**Issue by Thaodan** [sailfishos-sony-tama/main#80]
The defconfigs for every tama device have to be adjusted for hybris.
I already applied hybris fixes from 4.9 on top 4.14 here:
https://github.com/Thaodan/android_kernel_sony_msm/commits/hybris-sony-aosp-10.0.0

**Comment by rinigus** [comment]
Nice!

**Comment by rinigus** [comment]
Kernel config adjusted and is in hybris-10 branch https://github.com/sailfishos-sony-tama/android_kernel_sony_msm/tree/hybris-10.0-4.14
