### ISSUE TITLE
Use local_manifests with kernel 4.14 support enabled

### ISSUE THREAD

**Issue by Thaodan** [sailfishos-sony-tama/main#81]
Currently we use the stock local_manifests but we have to use this for kernel version 4.14 support:
https://github.com/sonyxperiadev/local_manifests/tree/android-9.0.0_r46a

**Comment by rinigus** [comment]
According to Sony devs, it was a mistake to add it there. To be more specific, it was/is used for TWRP and early work on kernel. As such, it has not been tested and is expected not to work anymore. The corresponding branch could be deleted in future as it served its purpose. So, we should not expect to be able to run 4.14 on AOSP9 and would have to wait for AOSP10 based port with it.

**Comment by MartinX3** [comment]
Just me used it for the TWRP I think

And yes, it was used for the 4.14 development, before 10 was ready.

But it was no mistake and you got a working ROM :P

**Comment by rinigus** [comment]
For us, it would be of interest if we can get 4.14 working as it is in the latest versions with the latest blobs. That would probably allow us to improve the camera. All the rest works well on SFOS, as far as I can tell and there is no reason to jump to another kernel. 

From what I understand, I cannot use latest 4.14 and latest blobs on AOSP9. Or do I understand wrong?

**Comment by Thaodan** [comment]
As far as I understand is the issue that we need to have newer userspace qualcom stuff as linked inside the manifest above. 
With the newer vendor libraries and the newer kernel it should work. The thing is that AOSP doesn't see much from the new kernel directly only the vendor libraries directly interface with the kernel and thus require an update. This requires that in our case droid-system and droid-system-vendor needs to be rebuild after the kernel update.

**Comment by MartinX3** [comment]
I made these changes for TWRP
https://github.com/MartinX3-AndroidDevelopment-OmniROM/local_manifests/commit/29125c682c67a8c5538a9434d7f94866b87fa649
https://github.com/MartinX3-AndroidDevelopment-OmniROM/repo_update/commit/c2488847982ab60256ffeb65c22a7ca33d834979

But I don't know if they are enough for a fully working sailfishOS

**Comment by rinigus** [comment]
New droid-system/vendor would require reflash. Which is nothing major iff the camera is working and users will do it. 

With all these updates we have to think strategically and not waste time on work that has to be redone or has high risk of failure. Hence my reluctance to start testing 4.14/AOSP9 base if it is not long-term solution.

In this respect, it is important to understand whether we can use latest and upcoming blobs on AOSP9/4.14. There was some chat on switching to CAF as well, not sure what it means for that. If @Thaodan has replied to it already, then I just didn't understand.

I have a feeling that for proper long-term support we will have to roll out AOSP10-based port anyway. That would be supported with the working blobs and we could use it later for as long as the port is alive.

Do my arguments make sense? 

@Thaodan: do you know whether you are alone working on AOSP10 port? 

@MartinX3: do you have some spare device where you could test AOSP9/4.14/latest blobs? Assuming that it is simple to build and you have such device around.

Meanwhile I am trying to get a separate device for development. Turns out to be non-trivial for Tama due to my location. But I hope to figure something out.

**Comment by MartinX3** [comment]
I sadly only have a single device
But i can put this research and development on my pile of todos for after my exams. :)

**Comment by rinigus** [comment]
No worries, maybe we will start with AOSP10 instead. Let's see what @Thaodan can tell as an insight regarding SFOS/AOSP10

**Comment by Thaodan** [comment]
>New droid-system/vendor would require reflash. Which is nothing major iff the camera is working and users will do it.
I was talking about the rpm package not the partition.

>@Thaodan: do you know whether you are alone working on AOSP10 port?
Yes currently I am the only person working on it.

**Comment by rinigus** [comment]
> I was talking about the rpm package not the partition.

I doubt we can rewrite /system and /vendor while system is booted by installing them from RPMs. But this is probably not the main concern. 

> Yes currently I am the only person working on it.

That what I was suspecting.

@Thaodan, if you have time and possibility to test AOSP9/4.14, feel free to do so. Personally, I have a feeling that it is not going to work, but you probably know system better. 

@MartinX3, for blobs and new kernel to work, I presume that we need to update devices to the latest stock as well? To get all the drivers updates. And if we want to get back to plain AOSP9, we would have to use Windows Emma tool for downgrading first. Right?

**Comment by Gouster4** [comment]
"for blobs and new kernel to work, I presume that we need to update devices to the latest stock as well?"

Its always recommended to update basebrand when new stock comes out.

**Comment by MartinX3** [comment]
Yes, flashing the newest stock (firmware and these partitions update) and fullfilling the google introduction setup is mandatory.
At the end it tells you, that the phone will restart, if there is a new baseband update getting installed.

About the downgrade
Using a 9.0 custom rom still works
I assume it is fine for SailfishOS as well

**Comment by rinigus** [comment]
@MartinX3, interesting. On official Sailfish X devices (X, XA2, 10), I think we are told to downgrade stock to the corresponding Android version of the port before flashing. There was some exception later, but I don't remember which exactly. If AOSP9 works after flashing stock Android 10, SFOS should work as well. So, that simplifies a bit the development.

**Comment by Thaodan** [comment]
@rinigus That was an issue with the display firmware upgrade from 8 -> 9.

**Comment by rinigus** [comment]
Managed to get Apollo for development. Looks like you could flash working SFOS directly over Android 10 stock, providing that you use correct OEM drivers. Will update flashing instructions and can start testing AOSP10 and it's camera

**Comment by rinigus** [comment]
Closed as 4.14 is in AOSP10 based port
