### ISSUE TITLE
Charger messages and behavior

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#87]
When you plug in a charger it shows various messages (Charging...) and these messages include the one that used to be shown when you unplug the charger. (unplug charger to save energy etc). Also the screen doesn't light up when you unplug the charger. 

Anyone sees this. And more importantly anyone sees this on a supported device???

**Comment by rinigus** [comment]
I cannot reproduce it, nor on wall charger, nor on wireless. 

- on start of the charging, I get screen on and message Charging... No other messages.
- on stop, wall charger: screen lids up, message about saving the energy is shown
- on stop, wireless: screen lids up, no messages.

I think it was the same before.

From your description, I would suspect bad contact. Either something is wrong with the charger, USB port, cable. Which is unpleasant angle to look at

**Comment by ApostolosB** [comment]
OK. I tested with another charger and it works fine.

**Comment by rinigus** [comment]
Nice! I am happy it is a charger, not the USB port on phone :)

**Comment by ApostolosB** [comment]
It seems to be kind of weirder than that. Its a usb-c charger (Anker PowerPort Atom PD2). If i plug a usb-c to usb-c cable it happens. If i use a dongle (on the charger side) and a normal usb to usb-c cable it works normally. I kind of suspect the charger doing something "smart".

Anyway all in all this is not bug.

**Comment by rinigus** [comment]
This charger could use some incompatible fast-charge mode ("smart"). So, I guess that happened.
