### ISSUE TITLE
Dev tools show password doesn't accept fingerprint.

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#89]
Go to Developer tools tap the abc button. It shows a security code page and only accepts the code. It doesn't work with the fingerprint.

**Comment by rinigus** [comment]
I think, in 3.4, there are several security based dialogs that accept code only. As for the first login after boot (that was in the release notes somewhere). Don't think it is an issue, closing. Please reopen if the official device does it differently
