### ISSUE TITLE
No fingerprint & haptic feedback (for the fingerprint) on security code screen after reboot

### ISSUE THREAD

**Issue by ApostolosB** [sailfishos-sony-tama/main#90]
After a reboot when presented with the security code screen the fingerprint works but haptic feedback doesn't work.

**Comment by rinigus** [comment]
Really strange. After reboot, I don't have fingerprint working (as expected in the release), but haptic is fine. Tested on OTA updated and on cleanly flashed devices. With and without SIM. 

Try to check whether your OTA did finish the update and make sure that jolla-configuration-xxxx is still installed.

**Comment by ApostolosB** [comment]
haptic doesn't work only on the initial security code. not in general.

**Comment by ApostolosB** [comment]
OK. I rebooted again. It doesn't accept the fingerprint also on the initial security screen. This used to work fine. It just didn't have haptic.

**Comment by rinigus** [comment]
I do have haptic on that first login screen.

**Comment by ApostolosB** [comment]
Haptic feed back for the fingerprint i mean. The buzz after you touch the reader. For typing it works.

I wasn't very clear with the way i typed it.

**Comment by rinigus** [comment]
Fingerprint is ignored for the first login in SFOS 3.4. You have to type the code. 

See https://forum.sailfishos.org/t/release-notes-pallas-yllastunturi-3-4-0/2258#device-lock

Closing as it is expected for this release
