### ISSUE TITLE
xz3 rebooting circle behaviour

### ISSUE THREAD

**Issue by pagism** [sailfishos-sony-tama/main#92]
I got a strange behaviour on my xz3, i noticed it got rebooted on its own, after reboot there is spinning circle and it cannot progress any further than that. The quick access menu is accessible and some operations work e.g. flash light, I can change the ambience and take pictures too. Anything else shows a spinning circle and leads to a reboot.

Is there any way breaking that vicious rebooting circle?

**Comment by rinigus** [comment]
Sorry to hear that. I don't know what can cause it and never seen something like it. Most probably you would have to reflash. But before that, try to take out sdcard, sim to change HW config and see if it helps.

**Comment by pagism** [comment]
Thanks, it seems I have to reflash, as I have an issue with cell connection too. That's an old issue I had with 3.2, but upgrading to 3.3 cell that issue had gone. With 3.4 it came back, actually this time the cell network symbol at the top right corner toggles between a dashed upside down triangle and a rectangle.
Btw do I have to reflash it back to stock OEM android image?

**Comment by rinigus** [comment]
No, I don't think you have to reflash to stock. Try to flash SFOS 3.4 and see if it gets resolved. If not, test whether it works on Android.

**Comment by pagism** [comment]
Update trying to flash SFOS 3.4, fastboot and flash.sh run without errors, the device boots but fails to turn on WiFi, when I skip it, I have to enter manually date/time, and go through the tutorial, half way through the tutorial it reboots ;-(  (I did this twice with same results). I think I have to reflash it back to android.

**Comment by rinigus** [comment]
Have you tried to 

- boot into SFOS after flash, 
- skip WiFi, make the rest of setup
- reboot
- try to enable WiFi

Some ports have issues with WIFI on the first boot. Occasionally, I think it was reported for Tama as well (or at least inability to login into Jolla Store). So, it may make sense to test.

If you already flashed Android, please report back regarding it

**Comment by pagism** [comment]
The main issue I have is the same I had yesterday, i.e. the device boots, but then within a couple of minutes it turns off and restarts. That couple of minutes are not enough to go through the initial steps, anyway, I managed to skip those and it shows a spinning circle. I can access the top drop-down menu, but not access much there, e.g. torch working, I can open the camera take and view a picture, but anything else shows a black screen with a spinning circle and then reboots (most likekely runs out of resources).  BTW does Emma now requires registration with a user name?

**Comment by rinigus** [comment]
OK, then it makes sense to test with Android. Regarding Emma I don't know. Good luck and let me know how it went.

**Comment by pagism** [comment]
I got stuck with sony emma account activation ;-( that might be  trikcy as I need to contact my Sony Representative (lol)

**Comment by rinigus** [comment]
Really? I wonder if you actually need Emma. As far as I remember, you could download stock ROM using XperiFirm and flash it with Newflasher. Both should be available on XDA

**Comment by pagism** [comment]
maybe XperFirm could do the trick too, testing Android now, it's a bit worrying mobile signal on this phone is very weak compared to XA2

**Comment by rinigus** [comment]
I would have not expected XZ3 having lower signal than XA2. But could be some particular network/sim card difference. Good luck with the testing!

**Comment by pagism** [comment]
Thanks, I switched back to android, but I still get the same misbehaviour on wifi and cell connections, it seems the more I try the worst it becomes, it must be possessed!

**Comment by rinigus** [comment]
Do you get that on stock as well? If you do, it is probably some hardware issue. Warranty should be still there if you are in EU

**Comment by pagism** [comment]
I had officially serviced an Xperia X in the past, but I was not impressed tbh. On android 9 now and after a lot of effort to make connections enabled it started working but while I am typing this message i noticed the phone just rebooted itself, when it does that all networking is somehow disabled, very erratic. I might lock the bootloader and try my luck with the service department, (yes officially in EU for a couple of weeks only ;( ).

**Comment by pagism** [comment]
I am going to close this issue as I am not convinced it's a porting issue. My latest reflash with Android shows an erratic behaviour too, but I am not convinced it's a hw issue either. None of the basic tests fails including WiFi, however something turns off connections and that causes rebooting after a while, STAMINA mode is off but there might be another Android process that tries to take care of the device?

Anyway, this morning I've reflashed SFOS and wifi connection seems stable and no reboots so far, no cellular connection tho. I will keep it running with SFOS for a couple of days to verify there are no reboots or wifi issues, but long term I need to find a suitable android image and bring back modem connectivity.

**Comment by rinigus** [comment]
Let's hope for the best and see if it will stabilize

**Comment by pagism** [comment]
apparently for newer xperia devices the bootloader cannot be re-locked, still tho sony companion sw is refusing to "repair" a device which is unlocked. if that's the case why it asks me to relock the device each time it boots?

**Comment by MartinX3** [comment]
> apparently for newer xperia devices the bootloader cannot be re-locked, still tho sony companion sw is refusing to "repair" a device which is unlocked. if that's the case why it asks me to relock the device each time it boots?

Since Xperia 1/5 & 10II you can relock xperias.

**Comment by pagism** [comment]
On Monday, 14 December 2020, Martin Dünkelmann wrote:
> 
> Since Xperia 1/5 & 10II you can relock xperias.
> 

Still doesn't make sence, why they support an AOSP and don't allow unlocked devices to be checked  from their publically available tools.

-- 
Sent from my Jolla

**Comment by MartinX3** [comment]
> On Monday, 14 December 2020, Martin Dünkelmann wrote: Since Xperia 1/5 & 10II you can relock xperias.
> Still doesn't make sence, why they support an AOSP and don't allow unlocked devices to be checked from their publically available tools.
> […](#)
> -- Sent from my Jolla

SODP is a different company department independent of the stock department.
That's normal in a big company.

**Comment by pagism** [comment]
@MartinX3 I think I've exhausted all possible things I can do with this device, SONY might be able to a bit more but how to approach them with an unlocked bootloader? does it make sense ask their support?

**Comment by MartinX3** [comment]
@pagism I saw a similiar reboot issue for users using an exFAT sdcard or using a single sim build on a dual sim device (without applying our dual sim patcher via recovery)

Does the same thing happen with plain stock and a fresh wiped device? (Flashing everything in newflasher what got downloaded via xperifirm)

If it's about a sdcard with an unsupported filesystem (exfat), it got fixed since SODP AOSP 10, the exfat tools and kernel 4.14

**Comment by pagism** [comment]
@MartinX3 it's single sim phone, and I have not used an sd card. The erratic behaviour is connectivity either wifi or cellular or both and is observed on both stock android 9/10 and sfos 3.4, hence I do not think it's a sfos issue. It might be an issue with flashing, as on a "bad" flash wifi MAC address and IMEI are blank, like these components they do not exist. On a "bad" flash the phone is on a constant reboot cycle, on other flash attempts rebooting can still happen without a reason in different intervals e.g. hours. I also noticed in all those cases cellular connection is a rarity. None of the sony diagnostic tests fails including the wifi unit if a MAC address is recognised. I think it's hw issue, e.g. deteriorating memory component? I managed to generate diagnostic reports but without connectivity is impossible to take them off the device.

**Comment by MartinX3** [comment]
@pagism The stuff like your MAC is saved on a partition of the UFS storage.
The chance that your UFS is dying should be low.
Important crash reasons should be written in the pstore
Or if you boot the phone with usb connected to your pc and do a `logcat -b all` into a file could reveal the crash reason.
Maybe simply a partition like persist got some wrong stuff in it.
I mean I never heard about this problem, so I doubt it is a hardware fault, but maybe you're the first one. :(

**Comment by pagism** [comment]
logcat has all sorts of errors no clue what can be the actual cause of the error.

**Comment by pagism** [comment]
@rinigus when I reverted my misbehaving XZ3 back to android, I followed Jolla's zendesk [guidelines](https://jolla.zendesk.com/hc/en-us/articles/115004283713-Reverting-Xperia-device-to-Android-OS-and-reinstalling-Sailfish-OS) and use Sony' Emma tool to reflash an OEM image.

Do I have to take extra steps before reverting? Android system logs, as @MartinX3 suggested,  show some /dev/block/loop devices missing or not found in the  beginning of system session.

**Comment by MartinX3** [comment]
@pagism Emma should reflash your operating system, not just the OEM partition

You could download and flash your device with xperifirm and newflasher
I think on emma was an older firmware.

**Comment by rinigus** [comment]
@pagism: try with the latest Sony stock in this case. Let's see if it helps you. xperifirm and newflasher are quite nice, never used Emma in my case.

**Comment by pagism** [comment]
@rinigus I've flashed the phone about a year ago from 52.0.A.11.32 to SFOS v3.2. I've noticed loosing cellular signal [#62](https://github.com/sailfishos-sony-tama/main/issues/62). Upgrading to SFOS v3.3 cellular connection was stable. SFOS v3.4  cellular connection was an issue again. Apart from that everything else was working ok, a week later the phone could not unlock, there was a spinning circle which occasionally reboot the phone.

I've re-flashed SFOS, went straight to 3.4, but during setup WiFi network could not be enabled, I thought I'd better revert to android.

I used EMMA initially and the options I found are 52.0.A.3.84, 52.0.A.8.131, and 52.1.A.0.618. I've tried all of them several times, on a 'good' flash MAC address and IMEI were identified and everything was working fine for some time, but then it started rebooting again. On a 'bad' flash the device is just rebooting constantly. Between those re-flashes I tried SFOS the behaviour was very similar to android one i.e. working fine then unable to unlock leading to reboot.

I can use adb and get some logs but I there is nothing very obvious, it seems to be very tolerant and moving on until the next reboot. Android self tests all pass, if a mac address is detected the wifi test passes too (otherwise it's disabled).

I've also contacted Sony Service, I have to admit the guy at the other end was very polite and eager to help me, I got a service code but I have not told him the device has an unlocked bootloader, so I might not be able to push on that side much further. BTW I found out that XZ devices once unlocked the bootloader cannot be locked again! Also Sony Companion(?) cannot repair an unlocked bootloader device ;-(

Today I used xperifirm and newflasher, the available fw I found was 52.1.A.3.92, apparently Sony removes old  versions. Flashing run smoothly, setup failed to find any networks and a new rebooting cycle started.

As you can see I am really running out of options now. I am afraid is a hw issue for whatever reason, maybe I will start looking for a replacement or swap m/b, or find an XZ2 one. lt is really a nice device and SFOS runs very smoothly on it, a lot better compared to XA2.

**Comment by rinigus** [comment]
I wonder what will happen if you give it to Sony. Using the last days of EU. Just would have to notify them about unlocked bootloader and make sure they will not slap some charge in this case.

**Comment by pagism** [comment]
I think the Sony procedure for unlocked bootloader devices is very clear, first they will replace the motherboard, then they will service the phone and asked for a big bill, I will ask tho. I had issues in the past with official service, these devices are not supposed to have replaceable parts, FairPhone is an exception but that's a different story.

**Comment by pagism** [comment]
@rinigus I've contacted Sony support, and surprise surprise, I was referred to book a service, which means I have to post the phone to service and they give me a quote for the repair. Unfortunately the 24 month guarantee has expired about a month ago, but having the bootloader unlocked wouldn't had helped.

Searching a bit more, there are similar behaviours, e.g. no IMEI number network issues, when the EFS partition is corrupted. Also the unlock bootloader pages recommends to disable "My Xperia" before the unlock, but that info appears after the unlock instructions, and I cannot remember disabling that service explicitly before unlocking. Maybe the last two points (EFS backup, disable My Xperia) should be highlighted in the README.md of this project?

**Comment by rinigus** [comment]
Re My Xperia: never heard of that

Re EFS backup: good idea, could you provide instructions for it? In particular, which partition is that? 

@MartinX3 - any other tips to include?

**Comment by MartinX3** [comment]
@rinigus 
https://play.google.com/store/apps/details?id=ma.wanam.partitions
There you can choose the partitions you wish to backup :)

**Comment by pagism** [comment]
Yet another update: after the nth reflash to Android Pie, and among TWPR recovery attempts and partition deletion, the phone starting working without issues for the past 48+ hours! Zero confidence tho as I am not sure what is changed or how long it will last. The only difference this time is the SD card in it, and a fully charged battery.

On erroneous mode IMEI and MAC IDs are missing, there might something else missing too and causes the phone to reboot. The rebooting cycle can either be continuous, or crash after a minute or so. Sometimes it can work OK for an hour and then lose networking and progressively start an endlessly rebooting cycle. It is really tricky within those cycles to complete setup and enable debugging mode. Reverse USB tethering also failed, most likely missing windows drivers.

The phone has the bootloader unlocked, but it's not rooted. EFS partition is not accessible, same for modemst{1,2} but  do no know much about those, I found a link suggesting deleting those partitions as the system will rebuild them and I guess it cannot be done without rooted. In TWRP recovery mode the phone was stable but I was not able to enable networking or reading IMEI/MAC info, actually it might not be possible.

Mis-configured battery subsystem might cause an issue with turning off radio modules. After the release of SFOS 3.4 the phone was off mainly for about two months with ~40% battery level and few brief turn on/offs. Has that caused the issue? it's not clear.

Comparing logcats the erroneous modes I see the following section which does not appear when it works ok:
> 
 --------- beginning of radio
12-26 20:30:58.074  1123  1123 E PDC_UTIL: pdc_info init done
12-26 20:30:58.079  1123  1123 E PDC_UTIL: qmi_client_init returned failure (-3) for PDC, retry times 0
12-26 20:30:58.428  1334  1334 I liblog  : 194
12-26 20:30:58.546  1512  1512 D RILD    : **RIL Daemon Started**
12-26 20:30:58.546  1512  1512 D RILD    : **RILd param count=1**
12-26 20:30:58.546  1512  1512 D RILD    : RIL_Init argc = 3 clientId = 0
12-26 20:30:58.547  1512  1512 E RILD    : deviceInfoServiceModule dlopen failed ERROR:dlopen failed: library "/vendor/lib64/deviceInfoServiceModule.so" not found
12-26 20:30:58.547  1512  1512 E RILQ    : log to /data/vendor/radio/ril_log for QCRIL logging is not enabled
12-26 20:30:58.547  1512  1512 E RILQ    : Fail to initialize Diag for QCRIL logging
--------- beginning of system

/vendor is mounted from /dev/block/dm-1 but I could not find more about that.
