### ISSUE TITLE
Flashing (IR-)light not stoping

### ISSUE THREAD

**Issue by HrGaertner** [sailfishos-sony-tama/main#93]
Hello i noticed that the battery of my xperia XZ3 (single sim) does not hold as long as om android. Now i might have the solution for this: When i showed my phone in my webcam i noticed a continously flashing light, which i clould not see with my eyes. Even an hour later it did not stop. A reboot does not help

Any ideas?

**Comment by rinigus** [comment]
I don't have any flashing light (checked with webcam to see IR). I have constant light (at least when webcam is close) on the top left. Now, I am not sure it accounts for the difference with Android.

So, few questions:

- which Android do you compare to? AOSP9 or stock?
- Have you checked whether that light is there for Android?
- Does this light work always, also with the screen off and phone in fully idle? As few minutes on desk and check then...

**Comment by HrGaertner** [comment]
1. The default xperia android
2. How do you mean this should i check wheter it stays when i stop android support? That does not help
3. No, still the same

I'll provide a video

Thanks a lot~ 

Am Freitag, 18. Dezember 2020 schrieb rinigus:

**Comment by HrGaertner** [comment]
Here is the file

https://user-images.githubusercontent.com/53614377/102636731-504a3c00-4155-11eb-846e-f9e836fa0a71.mp4

**Comment by rinigus** [comment]
I mean if you have Android flashed on your Xperia, do you also see the flashing light?

As for Android on SFOS, that is not supported on unofficial ports

**Comment by pagism** [comment]
I have my (most likely broken) XZ3 testing on android at the moment, that flashing light is not always on, when on sleep it might have a brief flash, sometimes flashing can go on for few minutes, but there are periods that is completely off.

**Comment by rinigus** [comment]
@pagism - thanks for the detail. I presume it is proximity sensor. @HrGaertner, try to wait some time with the phone inactive (20min for good measure) and check then. BTW, does your phone enter the sleep? You could check it either with SystemDataScope or System Monitor [fork].

Note that it is not necessary the cause for the battery consumption difference

**Comment by HrGaertner** [comment]
No even after a night the light flashed (does it make a diffrence wheter the phone is plugged?)

**Comment by rinigus** [comment]
@HrGaertner , please unplug the phone. For Sony Tama, CPU can sleep while charging on USB, but it is shorter than usual. At least for XZ2. So, unplug, wait 20 min and then check. Also, please check CPU sleep stats with the software listed above. It is vital to understand whether in your case it enters the sleep or not. And for how long. 

I am looking for stats as in https://openrepos.net/sites/default/files/packages/6933/screenshot-screenshot-16-07-09-10-24-09.png and under that.

**Comment by lal883** [comment]
Could that be the proximity sensor doing its thing. A friend sent me the video of his XZ2 yesterday which was running stock Android and I noticed the same purple short bursts on the top left corner. Phone had no SIM inserted, but screen ON.

**Comment by HrGaertner** [comment]
Ok, thanks! I was quite busy of christmas so I could not answer. Sorry for this! (By the way Happy new year!) The light did not stop after 30 Minutes although it seemed like most of the processes sleeped.
![github](https://user-images.githubusercontent.com/53614377/103655742-fb396300-4f67-11eb-9875-e38184496227.jpg)
![github2](https://user-images.githubusercontent.com/53614377/103655750-ff658080-4f67-11eb-8534-f043e08ab385.jpg)

**Comment by rinigus** [comment]
Please report CPU Sleep stats (click on CPU Overview and it should be shown there).

**Comment by HrGaertner** [comment]
Finally after waiting a few hours the light stopped flashing. The CPU sleep states looked like this at that time:
![photo_2021-01-12_08-23-06](https://user-images.githubusercontent.com/53614377/104282475-6971ae80-54af-11eb-9133-2535483cbdc2.jpg)
But i already had lower CPU states and the light did not stop flashing

**Comment by rinigus** [comment]
These states look to be similar to what I have with the network. So, it seems like the flashing does not interfere with it. To be sure that we are not masking anything by net, switch phone to offline network (no data on SIM and no wifi, calls could be on) and check then. CPU sleep should hit 85-90% in these conditions if all is OK

**Comment by HrGaertner** [comment]
After waiting three hours the light did not stop. On the weekend i can wait longer. Here are the states after those hours without any connections

![photo_2021-01-21_20-03-00](https://user-images.githubusercontent.com/53614377/105399336-c5f96a00-5c23-11eb-9a37-c8fac3f52d09.jpg)

**Comment by HrGaertner** [comment]
I had no app open and i am a little bit confused by those graphs

**Comment by rinigus** [comment]
Don't be confused, the look very good. CPU sleep shows that very large % of the time, phone is in sleep state. When it wakes up, it does it's tasks (like checking whatever it needs to check) and the CPU usage is for that active period of time. From this I conclude that flashing light does not interfere with CPU sleep and battery usage should not be majorly impacted by it.

**Comment by HrGaertner** [comment]
So i should just ignore the flashing light?

**Comment by rinigus** [comment]
Yes, I think you should just ignore it.

**Comment by HrGaertner** [comment]
Ok, thanks a lot!
