### ISSUE TITLE
Need to pull aliendalvik xa2 via xz2c I flashed the fishing sail os 3.4.0.24 xz2c when registering the jolla store I do not see some application in the license someone please help me without the sail fishing os without android it does not own little

### ISSUE THREAD

**Issue by chanhchua-been** [sailfishos-sony-tama/main#96]

**Comment by rinigus** [comment]
This is a community port and it does not support Aliendalvik nor licensed applications on Jolla Store. We cannot extend our support to it. It is clearly stated in the beginning of README in this repository.
